### ISSUE TITLE
[BUG] ERR_HTTP_HEADERS_SENT 

### ISSUE THREAD

**Issue by aetherwu** [SillyTavern/SillyTavern#1022]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Connect to mancer api (OK)
Mancer says connected as [mancer] Wizard Vicuna SuperHOT (OK)
SillyTavern crashes in console:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:377:5)
    at ServerResponse.setHeader (node:_http_outgoing:595:11)
    at ServerResponse.header (Project/SillyTavern/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send Project/SillyTavern/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (Project/SillyTavern/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (Project/SillyTavern/node_modules/express/lib/response.js:162:21)
    at ClientRequest.<anonymous> (Project/SillyTavern/server.js:789:28)
    at ClientRequest.emit (node:events:527:28)
    at RedirectableRequest.<anonymous> (Project/SillyTavern/node_modules/node-rest-client/lib/node-rest-client.js:721:39)
    at RedirectableRequest.emit (node:events:527:28) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

**Desktop (please complete the following information):**
 - OS/Device: MacOS 13.5 (22G74)
 - Environment: Local
 - Node.js version (if applicable): Node.js v18.3.0
 - Browser : Chrome
 - Generation API: Mancer
 - Branch: 1.9.7 'release'(1da5ea52)
 - Model:  Wizard Vicuna SuperHOT

**Comment by Cohee1207** [comment]
Hi. Please pull from the release branch and try again.

**Comment by aetherwu** [comment]
> Hi. Please pull from the release branch and try again.

It seems work now! Thanks!
