### ISSUE TITLE
[BUG] Vector Storage

### ISSUE THREAD

**Issue by OgalFinklestein** [SillyTavern/SillyTavern#1186]
### Environment

Self-Hosted (Bare Metal)

### System

Win10

### Version

1.10.4 'release' (6203d82f)

### Describe the problem

Just upgraded ST this morning via `UpdateAndStart.bat` because I saw the new Vector Storage feature.  Set the Vectorization Source to `Local (Transformers)` and proceeded to add to an existing chat.  Exception caught and displayed:

```Initializing transformers.js pipeline for task feature-extraction with model Xenova/all-mpnet-base-v2
TypeError: response.body.getReader is not a function
    at readResponse (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/utils/hub.js:572:34)
    at getModelFile (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/utils/hub.js:493:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getModelJSON (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 1)
    at async loadTokenizer (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/tokenizers.js:56:16)
    at async Function.from_pretrained (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/tokenizers.js:3777:48)
    at async Promise.all (index 0)
    at async loadItems (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:2110:5)
    at async pipeline (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:2056:19)
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by thijsi123** [comment]
Getting the exact same error when trying to 'Vectorize All', is there a fix/workaround for this?

```
Initializing transformers.js pipeline for task feature-extraction with model Xenova/all-mpnet-base-v2
TypeError: response.body.getReader is not a function
    at readResponse (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/utils/hub.js:572:34)
    at getModelFile (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/utils/hub.js:493:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getModelJSON (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 1)
    at async loadTokenizer (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/tokenizers.js:56:16)
    at async Function.from_pretrained (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/tokenizers.js:3777:48)
    at async Promise.all (index 0)
    at async loadItems (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:2110:5)
    at async pipeline (file:///H:/AI/SillyTavern-Launcher-main/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:2056:19)
```

**Comment by Cohee1207** [comment]
I don't have this issue, you both are likely having connection issues to HuggingFace where the models are downloaded from. You can preload the model manually and put it into ST/cache/Xenova/all-mpnet-base-v2 (create folders and put the downloaded files there).
https://huggingface.co/Xenova/all-mpnet-base-v2

**Comment by OgalFinklestein** [comment]
I'll give the manual download a try, but so far it looks like you're right.
```
git clone https://huggingface.co/Xenova/all-mpnet-base-v2
Recv failure: Connection was reset
```
Took me a few re-runs to clone the repo.

**Comment by thijsi123** [comment]
> I don't have this issue, you both are likely having connection issues to HuggingFace where the models are downloaded from. You can preload the model manually and put it into ST/cache/Xenova/all-mpnet-base-v2 (create folders and put the downloaded files there). https://huggingface.co/Xenova/all-mpnet-base-v2

Works perfectly!
What I did was;
Create cache/Xenova/ folders inside silly tavern folder, git clone https://huggingface.co/Xenova/all-mpnet-base-v2 into there.

**Comment by OgalFinklestein** [comment]
Yeah, confirmed.  That's the solution.
