### ISSUE TITLE
[BUG] Reverse Proxy Failing and crashing Sillytavern

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1248]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

SillyTavern 1.10.6 'staging' (9ee2c2e9)

### Desktop Information

- Node JS: v18.15.0
- Generation: OpenAI reverse proxy
- Branch: Staging
- Model: any gpt version

### Describe the problem

When I enter a reverse proxy for openai with it's secret key, it crashes giving the following error. 
I have searched for this error and I found an issue that was closed but I'm not sure if it's the same thing or relevent #1022. 

The steps to reproduce this are:
1. Enter reverse proxy information into the fields.
2. Press connect on the connection menu
3. Then it crashes with the following message.

```
TypeError: Cannot read properties of null (reading 'id')
    at C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\server.js:2766:57
    at Array.map (<anonymous>)
    at C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\server.js:2766:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ServerResponse.header (C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\node_modules\express\lib\response.js:174:12)
    at ServerResponse.json (C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\node_modules\express\lib\response.js:278:15)
    at ServerResponse.send (C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\node_modules\express\lib\response.js:162:21)
    at C:\Users\userhome\Desktop\Documents\AI\GitApps\SillyTavern\server.js:2776:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Press any key to continue . . .
```

### Additional info

This shows up after I connect.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/579b13e9-9a11-498d-8388-a928a22f74c1)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed the server-side crash.

**Comment by imesha10** [comment]
The issue is fixed! Thx, 🔥
