### ISSUE TITLE
[BUG] Vector storage error

### ISSUE THREAD

**Issue by UrBoiTom** [SillyTavern/SillyTavern#1321]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.10.7

### Desktop Information

Vectorization Source: Local (Transformers)

### Describe the problem

When I try to use the vector storage extra it says that the vectorization failed.

### Additional info

Error log:
```
Initializing transformers.js pipeline for task feature-extraction with model Xenova/all-mpnet-base-v2
Aborted(Error: ENOENT: no such file or directory, open 'C:\SillyTavern\SillyTavern-MainBranch\dist\ort-wasm-simd.wasm')
failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'C:\SillyTavern\SillyTavern-MainBranch\dist\ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.
Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'C:\SillyTavern\SillyTavern-MainBranch\dist\ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.)
Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'C:\SillyTavern\SillyTavern-MainBranch\dist\ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.
    at C:\SillyTavern\SillyTavern-MainBranch\node_modules\onnxruntime-common\dist\ort-common.node.js:6:11822
    at async m.create (C:\SillyTavern\SillyTavern-MainBranch\node_modules\onnxruntime-common\dist\ort-common.node.js:6:11480)
    at async constructSession (file:///C:/SillyTavern/SillyTavern-MainBranch/node_modules/sillytavern-transformers/src/models.js:124:16)
    at async Promise.all (index 1)
    at async MPNetModel.from_pretrained (file:///C:/SillyTavern/SillyTavern-MainBranch/node_modules/sillytavern-transformers/src/models.js:702:20)
    at async AutoModel.from_pretrained (file:///C:/SillyTavern/SillyTavern-MainBranch/node_modules/sillytavern-transformers/src/models.js:3371:20)
    at async Promise.all (index 1)
    at async loadItems (file:///C:/SillyTavern/SillyTavern-MainBranch/node_modules/sillytavern-transformers/src/pipelines.js:2110:5)
    at async pipeline (file:///C:/SillyTavern/SillyTavern-MainBranch/node_modules/sillytavern-transformers/src/pipelines.js:2056:19)
    at async Object.getPipeline (file:///C:/SillyTavern/SillyTavern-MainBranch/src/transformers.mjs:87:22)
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Run npm install to execute post-install script that copies the wasm files. If that doesn't help - copy the files from node_modules/sillytavern-transformers/dist to /dist in your installation directory.

**Comment by UrBoiTom** [comment]
I tried it but it didn't solve the issue. I believe the issue has something to do with the file requested by sillytavern (ort-wasm-simd.wasm) being different to the one in my dist folder (ort-wasm-simd-**threaded**.wasm)

**Comment by UrBoiTom** [comment]
I have managed to solve the issue by copying in the file (ort-wasm-simd.wasm) from another device but I feel like it isn't a very good fix.

**Comment by Cohee1207** [comment]
Did you have that file at all anywhere on your first device?
I can assume it was an error with the node package, it happens for some, rarely, and is not universal.

**Comment by UrBoiTom** [comment]
I had the threaded version but not the normal one on the device where it didn't work.
