### ISSUE TITLE
[Fetch failed]Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx not work

### ISSUE THREAD

**Issue by wujohns** [SillyTavern/SillyTavern#1474]
### Environment

Self-Hosted (Bare Metal)

### System

win10

### Version

1.10.9

### Describe the problem

The extra 'Character Expressions' not work
It can not download the model Cohee/distilbert-base-uncased-go-emotions-onnx correctly in China(because of the network reason with huggingface) and there is no way to set the proxy for transformer.js to slove it

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Download it manually, but in /cache/Cohee/distilbert-base-uncased-go-emotions-onnx
https://huggingface.co/Cohee/distilbert-base-uncased-go-emotions-onnx

**Comment by wujohns** [comment]
> Download it manually, but in /cache/Cohee/distilbert-base-uncased-go-emotions-onnx https://huggingface.co/Cohee/distilbert-base-uncased-go-emotions-onnx

Thanks, but how to get the cache dir path, or the rule of cache dir

**Comment by Cohee1207** [comment]
Cache directory is in the SillyTavern repository root folder (if it's not there - create it first).

**Comment by wujohns** [comment]
> Cache directory is in the SillyTavern repository root folder (if it's not there - create it first).

Thank you very much, it works !

**Comment by Katehuuh** [comment]
Manually download at "C:\SillyTavern\cache\Cohee\distilbert-base-uncased-go-emotions-onnx" still get error
```
Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx
std::bad_alloc
Error: Can't create session options
    at e.setSessionOptions (C:\SillyTavern\node_modules\onnxruntime-web\dist\ort-web.node.js:6:448766)
    at e.createSessionFinalize (C:\SillyTavern\node_modules\onnxruntime-web\dist\ort-web.node.js:6:450484)
    at e.createSession (C:\SillyTavern\node_modules\onnxruntime-web\dist\ort-web.node.js:6:451133)
    at e.createSession (C:\SillyTavern\node_modules\onnxruntime-web\dist\ort-web.node.js:6:443359)
    at e.OnnxruntimeWebAssemblySessionHandler.loadModel (C:\SillyTavern\node_modules\onnxruntime-web\dist\ort-web.node.js:6:446253)
    at Object.createSessionHandler (C:\SillyTavern\node_modules\onnxruntime-web\dist\ort-web.node.js:6:156059)
    at m.create (C:\SillyTavern\node_modules\onnxruntime-common\dist\ort-common.node.js:6:11932)
    at async constructSession (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/models.js:124:16)
    at async Promise.all (index 1)
    at async DistilBertForSequenceClassification.from_pretrained (file:///C:/SillyTavern/node_modules/sillytavern-transformers/src/models.js:702:20)
Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx
75644264
Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx
75644296
...
Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx
24
```

> Cache directory is in the SillyTavern repository root folder (if it's not there - create it first).
