### ISSUE TITLE
[BUG] <title>syntax error on both release and staging.

### ISSUE THREAD

**Issue by iplayfast** [SillyTavern/SillyTavern#1600]
### Environment

Self-Hosted (Bare Metal)

### System

linux mint

### Version

1.11.1? (pulled Dec 27)

### Desktop Information

node --version
v12.22.9

### Describe the problem

```
bash start.sh
Installing Node Modules...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'web-streams-polyfill@4.0.0-beta.3',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'signal-exit@4.1.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'write-file-atomic@5.0.1',
npm WARN EBADENGINE   required: { node: '^14.17.0 || ^16.13.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml@2.3.4',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

> sillytavern@1.11.1 postinstall
> node post-install.js

/home/chris/ai/aiprojects/SillyTavern/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/chris/ai/aiprojects/SillyTavern/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /home/chris/ai/aiprojects/SillyTavern
npm ERR! command failed
npm ERR! command sh -c node post-install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2023-12-27T07_41_57_586Z-debug-0.log
Entering SillyTavern...
/home/chris/ai/aiprojects/SillyTavern/node_modules/signal-exit/dist/cjs/index.js:162
        const ev = opts?.alwaysLast ? 'afterExit' : 'exit';
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/chris/ai/aiprojects/SillyTavern/node_modules/write-file-atomic/lib/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Node 12 version is too old and won't work. Versions starting from 18 should work

**Comment by iplayfast** [comment]
thanks for the quick reply!

**Comment by Sorry-Im-Stupid** [comment]
I've discovered that I also have this problem. 
So how exactly do we go about updating 'node' to a compatible version?
Is that Java?
Update: On the assumption that it is Java, I updated java to 22, and reinstalled SillyTavern. Still won't load, and according to the launcher it's still trying to use v12 like before.

``` 
Version & Compatibility Status:                              |
    SillyTavern - Branch: release | Status: Up to date
    SillyTavern: 1.13.1
    STL: 25.1.0.0
    Node.js: v12.22.9
```

**Comment by Cohee1207** [comment]
Java has nothing to do with that. Your Node version is too old. Update it.
Follow the instructions here:
https://docs.sillytavern.app/installation/updating/node/

**Comment by Sorry-Im-Stupid** [comment]
node -v reveals that I have v22.16.0
But the sillytavern launcher says 12.22.9
Do I have to install an independent instance in the sillytavern folder?

Update: I figured it out:
Launch the Launcher
Toolbox (option 6)
App Installer (option 2)
Core Utilities (option 4)
Install Node.js

(sorry about all the updates, been a weird day)

**Comment by Sorry-Im-Stupid** [comment]
Ok, it's a new day, and sillytavern is back to trying to use node v12, and the solution I discovered yesterday isn't working.

Edit: There is something wrong with the desktop link the installer made. When I run it from that, it tries to use node v12.
But if I run the launcher.sh directly in terminal, then it runs on node v22.

**Comment by Cohee1207** [comment]
Move this discussion to launcher repo.
