### ISSUE TITLE
[BUG] Error when sending messages through oobabooga API

### ISSUE THREAD

**Issue by trihardseven** [SillyTavern/SillyTavern#1725]
### Environment

Self-Hosted (Bare Metal)

### System

brave

### Version

1.11.3 staging

### Desktop Information

windows 10, latest oobabooga

### Describe the problem

It connects normally to ooba but when I send a message I get this error:
```

AttributeError: 'NoneType' object has no attribute 'startswith'
Exception in ASGI application
Traceback (most recent call last):
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 233, in __call__
    async with anyio.create_task_group() as task_group:
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    await func()
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\sse_starlette\sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\extensions\openai\script.py", line 104, in generator
    for resp in response:
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\extensions\openai\completions.py", line 531, in stream_completions
    for resp in completions_common(body, is_legacy, stream=True):
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\extensions\openai\completions.py", line 374, in completions_common
    generate_params = process_parameters(body, is_legacy=is_legacy)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\extensions\openai\completions.py", line 107, in process_parameters
    encoder = tiktoken.encoding_for_model(generate_params['model'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\tiktoken\model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\Text\OOgabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\tiktoken\model.py", line 80, in encoding_name_for_model
    if model_name.startswith(model_prefix):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'


```

### Additional info

The model loaded on ooba works normally on its own, only when trying to use it through ST this problem happens. I tried different models and same problem happens.

<img width="856" alt="brave_GbkJtJxrMI" src="https://github.com/SillyTavern/SillyTavern/assets/54422205/44053269-4e6c-4410-b55c-c75605638122">
<img width="736" alt="brave_XOXBbz3ofQ" src="https://github.com/SillyTavern/SillyTavern/assets/54422205/5f486acb-c762-4614-8d26-2590f8b26f8d">

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This relates to logit bias, it is currently broken in oobabooga's OpenAI API.
Wait for this to be merged: https://github.com/oobabooga/text-generation-webui/pull/5321

Alternatively, don't use logit bias.

**Comment by trihardseven** [comment]
removing logit bias worked, thanks

**Comment by kainatquaderee** [comment]
@trihardseven how did you remove logit bias?
