### ISSUE TITLE
[FEATURE_REQUEST] Possible to make SillyTavern available through the Scoop.sh package manager?

### ISSUE THREAD

**Issue by Spacellary** [SillyTavern/SillyTavern#1764]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Since SillyTavern/Extras is already distributed as a repository, would it be viable to offer distribution through the Scoop.sh package manager as way for even simpler installation, as it can make shortcuts/terminal shims for all the scripts and also offer even easier updates (and rollbacks through `scoop reset app@version`), and specially use of the "portable_config" folder, if you choose to take this a step further, keeping all user configuration and data inside a unified location that can be more easily backed-up (basically a single folder with everything the user needs to completely replicate their setup in another machine, but this **is** optional).

Scoop installations are entirely portable and the UX is generally pretty great...

...now, Scoop.sh is a Windows only utility, so I understand not catering for an specific OS, because by extension someone might say that "there should be packages for all package managers", but at the same time I genuinely believe it's a better user experience and an improvement for the platform where most users likely are.

If this is undesirable/not possible I understand and thanks for your time anyways.

### Describe the solution you'd like

Eg:
```pwsh
scoop install extras/sillytavern
scoop install extras/sillytavern-staging
scoop install extras/sillytavern-extras
```

### Describe alternatives you've considered

Other package managers aren't as flexible or as transparent, or graceful with portable installations, which is something that should be maintained.

### Priority

Low (Nice-to-have)
Just an idea for if there's an interest into this distribution channel.

**Comment by ghost** [comment]
Here is a quick solution, installation will be done by starting the app from the shortcut.

{
```
    "version": "1.11.2",
    "checkver": "github",
    "description": "SillyTavern is a user interface you can install on your computer (and Android phones) that allows you to interact with text generation AIs and chat/roleplay with characters you or the community create.",
    "homepage": "https://sillytavern.app/",
    "license": {
        "identifier": "AGPL-3.0",
        "url": "https://github.com/SillyTavern/SillyTavern?tab=AGPL-3.0-1-ov-file#readme"
    },
    "depends": "nodejs-lts",
    "url": "https://github.com/SillyTavern/SillyTavern/archive/refs/tags/1.11.2.zip",
    "hash": "3afbe1bb65e7a8a11685bf641dc96cbc9b67a4245ed3957eb980ea235d40f7eb",
    "extract_dir": "SillyTavern-1.11.2",
    "pre_install": "Copy-Item \"$persist_dir\\public\\st-launcher.ico\" \"$dir\\st-launcher.ico\" -ErrorAction SilentlyContinue",
    "bin": "Start.bat",
    "shortcuts": [
        [
            "Start.bat",
            "Silly Tavern",
            "",
            "st-launcher.ico"
        ]
    ],
    "persist": "public"
}
```

I added this to my own bucket and I am using it now. I don't use extras or staging.

PS: Nope, persist doesn't work. Keeps re-processing context. It works without persist. Could you take a look at this? Which folders needs to be in persist other than "public"?

**Comment by Spacellary** [comment]
I also tried a similar manifest but also without `persist`, in consideration to the built-in Vector Storage plug-in the `vectors` folder should also persist.
There are also the `secrets.json` and `config.yaml` files in the base SillyTavern directory, one holds the API keys, the other the general configuration for exposing the application on the network, which should persist if we're going that route, when we figure exactly what is the minimum needed.

**Comment by Spacellary** [comment]
I was having issues with using "shortcuts", so using only shim in post_install for now. to add the shim to `test-sillytavern` to Path:

```
{
    "version": "1.11.2",
    "checkver": "github",
    "description": "LLM Frontend for Power Users.",
    "homepage": "https://sillytavern.app/",
    "license": {
        "identifier": "AGPL-3.0",
        "url": "https://github.com/SillyTavern/SillyTavern?tab=AGPL-3.0-1-ov-file#readme"
    },
    "depends": "nodejs-lts",
    "url": "https://github.com/SillyTavern/SillyTavern/archive/refs/tags/1.11.2.zip",
    "hash": "3afbe1bb65e7a8a11685bf641dc96cbc9b67a4245ed3957eb980ea235d40f7eb",
    "extract_dir": "SillyTavern-1.11.2",
    "pre_install": "Copy-Item \"$persist_dir\\public\\st-launcher.ico\" \"$dir\\st-launcher.ico\" -ErrorAction SilentlyContinue ; Copy-Item \"$persist_dir\\secrets.json\" \"$dir\\secrets.json\" -ErrorAction SilentlyContinue ; Copy-Item \"$persist_dir\\config.yaml\" \"$dir\\config.yaml\" -ErrorAction SilentlyContinue",
    "post_install": [
        "shim \"$dir\\Start.bat\" $global test-sillytavern"
    ],
    "persist": [
        "public",
        "secrets.json",
        "config.yaml"
    ]
}
```
I'm running into issues when running `test-sillytavern` (Start.bat):

```
Command: test-sillytavern

C:\Users\Spacellary>pushd C:\Users\Spacellary\scoop\apps\test-sillytavern\current\

C:\Users\Spacellary\scoop\apps\test-sillytavern\current>call npm install --no-audit

> sillytavern@1.11.2 postinstall
> node post-install.js

ort-wasm-simd-threaded.wasm successfully copied to ./dist/ort-wasm-simd-threaded.wasm
ort-wasm-simd.wasm successfully copied to ./dist/ort-wasm-simd.wasm
ort-wasm-threaded.wasm successfully copied to ./dist/ort-wasm-threaded.wasm
ort-wasm.wasm successfully copied to ./dist/ort-wasm.wasm
FATAL: Could not add missing config values to config.yaml Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:453:20)
    at addMissingConfigValues (C:\Users\Spacellary\scoop\apps\test-sillytavern\1.11.2\post-install.js:79:36)
    at Object.<anonymous> (C:\Users\Spacellary\scoop\apps\test-sillytavern\1.11.2\post-install.js:201:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}

added 507 packages in 14s

79 packages are looking for funding
  run `npm fund` for details
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
Running from source
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
SillyTavern 1.11.2
node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:453:20)
    at readSecret (C:\Users\Spacellary\scoop\apps\test-sillytavern\1.11.2\src\endpoints\secrets.js:71:29)
    at migrateSecrets (C:\Users\Spacellary\scoop\apps\test-sillytavern\1.11.2\src\endpoints\secrets.js:102:21)
    at Object.init (C:\Users\Spacellary\scoop\apps\test-sillytavern\1.11.2\src\endpoints\settings.js:161:5)
    at Server.setupTasks (C:\Users\Spacellary\scoop\apps\test-sillytavern\1.11.2\server.js:615:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}

Node.js v20.11.0
Press any key to continue...
```

**Comment by ghost** [comment]
That is because there is no config.yaml before you run Start.bat, therefore you cannot persist it.

**Comment by Spacellary** [comment]
I see, and it seems those files I wanted to persist ("secrets.json", "config.yaml") are also only created afterwards by user input and do not come with the repo.

**Comment by Spacellary** [comment]
Let's keep the idea open just in case and for reference.

**Comment by ghost** [comment]
I think, now that there is a separate data folder, it could be done. I am using docker these days, but I will look into this soon.
