### ISSUE TITLE
[BUG] npm error: Invalid comparator: npm:dry-uninstall

### ISSUE THREAD

**Issue by anonymous721** [SillyTavern/SillyTavern#1943]
### Environment

Self-Hosted (Bare Metal)

### System

Debian 12

### Version

1.11.6

### Desktop Information

Node.js v18.19.0
Release branch.
I don't get far enough for APIs or models to be relevant.

### Describe the problem

Starting clean, I `git clone` the release branch, `cd` in, and run start.sh, but the script fails with the error given below.
Since it's an npm error, that was the first thing I checked. Node.js and npm are both up to date according to apt-get, and as the error message itself says, the Node.js version is above the v18 requirement stated in all the installation docs.

### Additional info

```
Installing Node Modules...
npm ERR! Invalid comparator: npm:dry-uninstall

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2024-03-18T01_37_56_785Z-debug-0.log
Entering SillyTavern...
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'open'
Require stack:
- /home/user/AI/SillyTavern/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/user/AI/SillyTavern/server.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/user/AI/SillyTavern/server.js' ]
}

Node.js v18.19.0
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Possible solutions:
1. Update npm `npm install -g npm@latest`
2. Update Node to 20. Using nvm: `nvm install 20; nvm use 20`. Other installation methods may vary.
3. (Least preferred) remove these three lines, including a preceding comma, from package.json, this is mainly a 32-bit Termux cope which isn't your case: https://github.com/SillyTavern/SillyTavern/blob/release/package.json#L51-L53

**Comment by donlinglok1** [comment]
I got the same issues and `npm install -g npm@latest` works for me! Thank you [Cohee1207](https://github.com/Cohee1207)!

> Possible solutions:
> 
> 1. Update npm `npm install -g npm@latest`
> 2. Update Node to 20. Using nvm: `nvm install 20; nvm use 20`. Other installation methods may vary.
> 3. (Least preferred) remove these three lines, including a preceding comma, from package.json, this is mainly a 32-bit Termux cope which isn't your case: https://github.com/SillyTavern/SillyTavern/blob/release/package.json#L51-L53

**Comment by Stratoco** [comment]
> I got the same issues and `npm install -g npm@latest` works for me! Thank you [Cohee1207](https://github.com/Cohee1207)!
> 
> > Possible solutions:
> > 
> > 1. Update npm `npm install -g npm@latest`
> > 2. Update Node to 20. Using nvm: `nvm install 20; nvm use 20`. Other installation methods may vary.
> > 3. (Least preferred) remove these three lines, including a preceding comma, from package.json, this is mainly a 32-bit Termux cope which isn't your case: https://github.com/SillyTavern/SillyTavern/blob/release/package.json#L51-L53

Also had the same issue, this worked for me too.

**Comment by 631068264** [comment]
```
(base) ➜  ~ node -v
v22.1.0
(base) ➜  ~ npm install -g npm@latest

changed 13 packages in 3s

24 packages are looking for funding
  run `npm fund` for details
  
node -v
v22.1.0
```
not work  still get same error
```
Installing Node Modules...

up to date in 199ms
Entering SillyTavern...
node:internal/modules/cjs/loader:1227
  throw err;
  ^

Error: Cannot find module 'open'
Require stack:
- /Users/wyx/project/SillyTavern-Launcher/SillyTavern/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1224:15)
    at Module._load (node:internal/modules/cjs/loader:1050:27)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/wyx/project/SillyTavern-Launcher/SillyTavern/server.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:168:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/wyx/project/SillyTavern-Launcher/SillyTavern/server.js' ]
}

Node.js v22.1.0

Saving session...completed.

```

**Comment by Cohee1207** [comment]
@631068264 
It's not the same error. Remove `node_modules` from the SillyTavern folder, clean the npm cache, and reinstall node_modules again with npm i.
