### ISSUE TITLE
[BUG] SilleyTavern postinstall script fails 

### ISSUE THREAD

**Issue by tegant** [SillyTavern/SillyTavern#1946]
### Environment

Other (Specify below)

### System

Ubuntu 20.04

### Version

Latest (can't install)

### Desktop Information

Azure Machine Learning VM (Nvidia Tesla T4)
Node v12.22.6, release

### Describe the problem

When running ./start.sh it crashes with this error message below.

### Additional info

```
(azureml_py38) azureuser@llm1:~/SillyTavern$ ./start.sh
Installing Node Modules...
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!

> sillytavern@1.11.6 postinstall /home/azureuser/SillyTavern
> node post-install.js

/home/azureuser/SillyTavern/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/azureuser/SillyTavern/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sillytavern@1.11.6 postinstall: `node post-install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sillytavern@1.11.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/azureuser/.npm/_logs/2024-03-22T09_43_40_971Z-debug.log
Entering SillyTavern...
/home/azureuser/SillyTavern/node_modules/signal-exit/dist/cjs/index.js:162
        const ev = opts?.alwaysLast ? 'afterExit' : 'exit';
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/azureuser/SillyTavern/node_modules/write-file-atomic/lib/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Node 12 is way too old and is not supported. Update to latest LTS release.

**Comment by tegant** [comment]
Thanks you for your response.

I'm on Ubuntu 20.04. I tried to install he latest like this:

```
sudo apt-get update
sudo apt-get install build-essential checkinstall libssl-dev
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
```

It was successful:
```
=> Downloading nvm from git to '/home/azureuser/.nvm'
=> Cloning into '/home/azureuser/.nvm'...
remote: Enumerating objects: 9308, done.
remote: Counting objects: 100% (2094/2094), done.
remote: Compressing objects: 100% (216/216), done.
remote: Total 9308 (delta 1981), reused 1912 (delta 1877), pack-reused 7214
Receiving objects: 100% (9308/9308), 3.61 MiB | 42.04 MiB/s, done.
Resolving deltas: 100% (5986/5986), done.
* (HEAD detached at v0.32.1)
  master
=> Compressing and cleaning up git repository
Enumerating objects: 9308, done.
Counting objects: 100% (9308/9308), done.
Delta compression using up to 4 threads
Compressing objects: 100% (9195/9195), done.
Writing objects: 100% (9308/9308), done.
Total 9308 (delta 6296), reused 2753 (delta 0), pack-reused 0

=> Appending source string to /home/azureuser/.bashrc
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:

/anaconda/envs/azureml_py38/lib
├── azure@2.3.1-preview
├── n@9.1.0

=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:

     $ nvm use system
     $ npm uninstall -g a_module

=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="/home/azureuser/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

`nvm --version` shows `0.32.1`.

Then I did this:

`nvm install node`

```
Computing checksum with sha256sum
Checksums matched!
Now using node v21.7.1 (npm v10.5.0)
Creating default alias: default -> node (-> v21.7.1)
```

This seems to have worked correctly.  Thank you.

**Comment by tegant** [comment]
I just realised what the problem is.   When I install Oobabooga and run it with `./start_linux.sh --share  --trust-remote-code` it force-installs node 12, and it breaks SillyTavern afterwards.

I have been following the docs here.  These steps won't work on the same machine:
https://docs.sillytavern.app/usage/local-llm-guide/how-to-use-a-self-hosted-model/

What should I do? Thanks

**Comment by Cohee1207** [comment]
I can't see this in the script and honestly, I'm not sure why ooba's WebUI needs Node since it runs Python.
Report this to: https://github.com/oobabooga/text-generation-webui/issues

Files checked:
https://github.com/oobabooga/text-generation-webui/blob/main/start_linux.sh
https://github.com/oobabooga/text-generation-webui/blob/main/one_click.py

**Comment by tegant** [comment]
I discussed it with Ooba team, there is no Node installed on their end.

So When I run SillyTavern I see how it installs Node, see below:
```
(azureml_py38) azureuser@llm2:~/SillyTavern$ ./start.sh
Installing Node Modules...
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!

> sillytavern@1.11.6 postinstall /home/azureuser/SillyTavern
> node post-install.js

/home/azureuser/SillyTavern/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/azureuser/SillyTavern/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sillytavern@1.11.6 postinstall: `node post-install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sillytavern@1.11.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/azureuser/.npm/_logs/2024-03-23T08_18_17_783Z-debug.log
Entering SillyTavern...
/home/azureuser/SillyTavern/node_modules/signal-exit/dist/cjs/index.js:162
        const ev = opts?.alwaysLast ? 'afterExit' : 'exit';
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/azureuser/SillyTavern/node_modules/write-file-atomic/lib/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

This action destroys the previously installed Node version `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash`

```
node -v
v12.22.6
```

Node is back to version 12. Even retrying to install the latest won't help, it stays on v12, see below:

```
(azureml_py38) azureuser@llm2:~/SillyTavern$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10250  100 10250    0     0   102k      0 --:--:-- --:--:-- --:--:--  103k
=> nvm is already installed in /home/azureuser/.nvm, trying to update using git
=> => Compressing and cleaning up git repository
Enumerating objects: 9308, done.
Counting objects: 100% (9308/9308), done.
Delta compression using up to 4 threads
Compressing objects: 100% (9195/9195), done.
Writing objects: 100% (9308/9308), done.
Total 9308 (delta 6296), reused 3011 (delta 0), pack-reused 0

=> Source string already in /home/azureuser/.bashrc
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:

/home/azureuser/.nvm/versions/node/v21.7.1/lib
├── corepack@0.25.2

=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:

     $ nvm use system
     $ npm uninstall -g a_module

=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="/home/azureuser/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
(azureml_py38) azureuser@llm2:~/SillyTavern$ node -v
v12.22.6
```

**Comment by tegant** [comment]
Ah I found the issue. It's something with Ubuntu's path.

If I run this manually:

```
export NVM_DIR="/home/azureuser/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

Then I can see nvm is loading and node shows as version 21.  SillyTavern now loads correctly.

Sorry for all these brainstormings here. I hope it helps somebody else in future.

**Comment by Cohee1207** [comment]
If anything, you can just skip start.sh and do these commands: `npm i; npm run start`. The script does nothing else really.

**Comment by Sorry-Im-Stupid** [comment]
I'm running Linux Mint and having a similar issue with the post-install of the launcher type.


```
Installing Node Modules...

> sillytavern@1.13.1 postinstall
> node post-install.js

file:///home/username/Stable/Tavern/SillyTavern-Launcher/SillyTavern/src/server-directory.js:3
export const serverDirectory = path.dirname(import.meta.dirname ?? path.dirname(fileURLToPath(import.meta.url)));
                                                                 ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR! code 1
npm ERR! path /home/username/Stable/Tavern/SillyTavern-Launcher/SillyTavern
npm ERR! command failed
npm ERR! command sh -c node post-install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2025-06-22T17_45_36_904Z-debug-0.log
Entering SillyTavern...
file:///home/username/Stable/Tavern/SillyTavern-Launcher/SillyTavern/server.js:12
    await import('./src/server-main.js');
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```

**Comment by Wolfsblvt** [comment]
@Sorry-Im-Stupid likely a very similar issue. If you made sure you have a valid node version installed that ST suports, and still run into those errors, then the issue lies with the SillyTavern launcher.
If you'd launch ST right via the launch scripts, it'll likely work.

Raise the issue in the [SillyTavern Launcher repo](https://github.com/SillyTavern/SillyTavern-Launcher/issues).
