### ISSUE TITLE
[BUG] Vector Storage - Generation interceptor aborted

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#2328]
### Environment

🪟 Windows

### System

Server: SillyTavern v1.12.0 hosted on Debian 11, Client: Firefox 126.0 (x64) on Windows 11

### Version

SillyTavern 1.12.0 'release' (56392c17)

### Desktop Information

- Node.js: v21.6.1 (on Debian 11)
- Generation API: koboldcpp v1.64.0 (on client side Win11)
- Branch: release
- Model: L3-8B-Stheno-v3.1-Q4_K_M-imat.gguf

### Describe the problem

I only use vector storage and translation active. My version 1.12.0 is not fresh, it is upgraded from v1.11.8 but without the new account feature.

**Here is the situation:** 
I have a chat with about 20-40 messages (or even more). After i got the answer from the AI that i do not like, i changed my last message and pressed the "right" arrow to create another answer. Sometimes, if i am very fast with these two clicks (changing my last message + re-create the API reply), an error occured.
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/68a5a6a1-e6ac-44a2-9b4a-66a8b7ee5344)

It seems to me that there is a small bug in the vector storage plugin.
After checking the console, as the error said, here is the output:
```
Vectors: Failed to rearrange chat Error: Failed to query collection 2024-5-13 @01h 37m 34s 865ms
```
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/e13a0522-e8fc-4fab-ac0c-c8241f775a4a)

As far as i remember, this error did never happen in v1.11.8 (or any other release version before).
It also appears in pre-1.12.0 existing chats including new v1.12.0 chats. 

The error only occurs when I perform both actions in quick succession. To me it looks like the following activities somehow overlap and create an access violation while reading from or writing into the vector storage the same time:
- "Delete old message, recalculate vector for changed message, save changed message plus vector"
- "Receive new AI response, calculate vector and save"

It is perhaps important to know that my AI response is generated within 2-5 seconds. According to Firefox's network analysis, the POST requests against "xxx/api/vector/query" seem to take about 4-5 seconds before an HTTP 500 error message is returned.
Is there any sort of locking mechanism or serialization for the vector storage access?

![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/b29a4f83-3954-4225-a15f-504e9b0b001a)

---

I should also tell that i run ST behind an nginx reverse proxy (both in a VM) to add TLS/SSL support. It could be that HTTP/2, which uses concurrent connections to improve performance, could cause this issue because of missing vector access serialization. 
I also know that you do NOT provide reverse proxy support and i am not here to ask for it. 😄 I just want to report that strange bug.

Thank you very much in advance

### Additional info

See above

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> As far as i remember, this error did never happen in v1.11.8 (or any other release version before).

The error was likely there, but not brought up to the frontend.

Check the server console. Also what is the embeddings provider.

**Comment by stho90** [comment]
That's a very good point!

Here is some strange console output. It seems that after the endpoint's response, another prompt is started, which is cut off halfway.

```
[...]
  grammar: '',
  rep_pen: 1.05,
  rep_pen_range: 1024,
  repetition_penalty_range: 1024,
  seed: -1,
  guidance_scale: 1,
  negative_prompt: '',
  grammar_string: '',
  repeat_penalty: 1.05,
  tfs_z: 1,
  repeat_last_n: 1024,
  n_predict: 250,
  mirostat: 0,
  ignore_eos: false
}
Endpoint response: {
  id: 'cmpl-1',
  object: 'text_completion',
  created: 1,
  model: 'koboldcpp/L3-8B-Stheno-v3.1-Q4_K_M-imat.gguf',
  usage: { prompt_tokens: 100, completion_tokens: 100, total_tokens: 200 },
  choices: [
    {
      text: "bla bla" +
        "bla bla" +
        '*She looked up at him, hoping to',
      index: 0,
      finish_reason: 'length'
    }
  ]
}
SyntaxError: Expected ',' or ']' after array element in JSON at position 3670016 (line 1 column 3670017)
    at JSON.parse (<anonymous>)
    at LocalIndex.<anonymous> (/root/SillyTavern/node_modules/vectra/lib/LocalIndex.js:337:31)
    at Generator.next (<anonymous>)
    at fulfilled (/root/SillyTavern/node_modules/vectra/lib/LocalIndex.js:28:58)
{
  prompt: '<|start_header_id|>system<|end_header_id|>\n' +
  [...]
```

I will try to create a separate test bot and try to reproduce the issue with that, to share the created vector storage. Maybe there is some fault data in the vector storage that prevents the JSON.parse from working, if the data is selected from the storage.

By the way, i have tested to bypass nginx with Node.js SSL from this comment https://github.com/SillyTavern/SillyTavern/issues/2025#issuecomment-2041309219 
It works without nginx too, changes HTTP/2 into HTTP/1.1 but the issue still occures sometimes. Not that frequently like before, but it does.

**Comment by Cohee1207** [comment]
No, it's much simpler - your vector index is corrupted. Purge and regenerate it.

**Comment by stho90** [comment]
> No, it's much simpler - your vector index is corrupted. Purge and regenerate it.

If only everything in life were that simple! Wow! I will try that and give you feedback. Thank you very much and sorry for the false trouble. 👍

**Comment by stho90** [comment]
Hello again,

here is a short update: I have updated to v1.12.1 and re-created the vector storage of an existing chat. After a few messages, i received the error message again. Here is the log message:

```
[...]
Corrupted index detected at data/default-user/vectors/transformers/Branch #47 - 2024-6-8@13h08m47s, regenerating...
Error: Index already exists
    at LocalIndex.<anonymous> (/root/SillyTavern/node_modules/vectra/lib/LocalIndex.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/SillyTavern/node_modules/vectra/lib/LocalIndex.js:28:58)
{
[...]
```

---

Update: It seems that this was a one-time error.

Update 2: Nope, it happened again in the same chat (after editing the last message and pressed "Continue"). Sometimes, i just like to delete the halve of the last generated message and press "Continue" to create the missing second half of the message. Then, his error happened again.

**Comment by fastfinge** [comment]
I get this error any time I run local vectorization for more than 10 messages or so. I've tried on multiple computers, both AMD and NVDIA, multiple browsers, with multiple character cards.

**Comment by fastfinge** [comment]
For anyone else struggling, the best thing to do is use Ollama for vectorization. Works faster even with CPU only, and never gets these errors.

**Comment by andrewc12** [comment]
I've also been getting issues that corrupt the vector storage
 might look into it when I get a bit more time

**Comment by vadash** [comment]
I still have this problem. After 1-2 hours of RP index can get corrupted. Happens when I send message. I tried local olama embed and gemini. My ST is latest 1.13.x, node 22.14, win 11. It maybe problem with Qvink summary plugin as well. I always had this problem but didnt had time to fix

I could probably fix it here, but it would take too much time getting familiar with codebase. I coded simple PS script that backups index from time to time and restarts ST when detects corruption. Thats not solution but may help others

https://github.com/vadash/silly_tavern_vector_monitor

I searched for "vector index is corrupted" in issues and only found 2 threads, this one is best to post imo

**Comment by LxKxC** [comment]
I suspect the problem is caused by resource exhaustion on the device hosting the embedding model (I'm using Ollama running in Docker on my laptop) (or a problem with the embedding model itself). When I first used the `embeddinggemma` model, I encountered a "Vector Storage - Generation interceptor aborted" error, but after switching to "qwen3-embedding:0.6b", I haven't had any issues so far.

**Comment by aelfwyne** [comment]
This needs to be re-opened. The bug is still present. 

I'm having this same issue. The problem appears to be that using "Continue" repeatedly causes the internal vector storage to overflow past its chunk size, causing corruption of the vector storage file. 

The error I get in the UI is: 
```
Vector Storage
Generation interceptor aborted. Check browser console for more details. ..
```

When I check F12: 
```
Vectors: Failed to rearrange chat
Error: Failed to query multiple collections
    at queryMultipleCollections (index.js:1197:15)
    at async activateWorldInfo (index.js:1706:26)
    at async rearrangeChat (script.js:792:13)
    at async runGenerationInterceptors (extensions.js:2028:17)
    at async Generate (script.js:4505:25)
    ...
```

And in the Sillytavern log I get a massive spam which I've clipped out the repetitive bits of:

```

std::bad_alloc
An error occurred during model execution: "Error: failed to call OrtRun(). error code = 6.".
Inputs given to model: [Object: null prototype] {
  input_ids: Tensor {
    dims: [ 1, 4315 ],
    type: 'int64',
    data: BigInt64Array(4315) [
        101n, 12849n,  6499n,  2506n,  2551n,  2014n, 22418n,  2007n,  2010n,
       4416n,  1998n,  4344n,  1010n,  2551n,  2000n,  5676n,  2008n,  2016n,
       2038n,  2012n,  2560n,  2028n,  1010n,  2030n,  2672n,  2048n,  1010n,
      13892n,  2015n,  2077n,  2002n,  3138n,  2014n,  1012n,  1031n,   100n,
       2051n,  2340n,  1024n,  2321n,  1064n,   100n, 19348n,  2475n,  1011n,
       5840n,  1011n,  2861n,  1010n,  1064n,   100n,  2530n, 22944n,  1011n,


---- thousands and thousands of lines removed ------


       6718n,  1010n, 15080n,  2068n,  1996n,  4223n,  2027n, 25155n,  1012n,
       1026n,   999n,  1011n,  1011n,  1043n,  2546n,  2595n,  1035n,  2203n,
       1011n,  1011n,  1028n,   102n
    ],
    size: 4315
  },
  attention_mask: Tensor {
    dims: [ 1, 4315 ],
    type: 'int64',
    data: BigInt64Array(4315) [
      1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n,
      1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n,
      1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n,


---- thousands and thousands of lines removed ------


      1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n,
      1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n,
      1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n, 1n,
      1n, 1n, 1n, 1n, 1n, 1n, 1n
    ],
    size: 4315
  },
  token_type_ids: Tensor {
    dims: [ 1, 4315 ],
    type: 'int64',
    data: BigInt64Array(4315) [
      0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n,
      0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n,
      0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n,
      0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n,

---- thousands and thousands of lines removed ------

0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n,
      0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n, 0n,
      0n, 0n, 0n, 0n, 0n, 0n, 0n
    ],
    size: 4315
  }
}
Error: failed to call OrtRun(). error code = 6.
    at e.run (/home/aelfwyne/SillyTavern/node_modules/onnxruntime-web/dist/ort-web.node.js:6:454392)
    at e.run (/home/aelfwyne/SillyTavern/node_modules/onnxruntime-web/dist/ort-web.node.js:6:443740)
    at e.OnnxruntimeWebAssemblySessionHandler.run (/home/aelfwyne/SillyTavern/node_modules/onnxruntime-web/dist/ort-web.node.js:6:446675)
    at m.run (/home/aelfwyne/SillyTavern/node_modules/onnxruntime-common/dist/ort-common.node.js:6:9992)
    at sessionRun (file:///home/aelfwyne/SillyTavern/node_modules/sillytavern-transformers/src/models.js:207:36)
    at Function.encoderForward [as _forward] (file:///home/aelfwyne/SillyTavern/node_modules/sillytavern-transformers/src/models.js:520:18)
    at Function.forward (file:///home/aelfwyne/SillyTavern/node_modules/sillytavern-transformers/src/models.js:820:27)
    at Function._call (file:///home/aelfwyne/SillyTavern/node_modules/sillytavern-transformers/src/models.js:809:27)
    at Function.closure [as model] (file:///home/aelfwyne/SillyTavern/node_modules/sillytavern-transformers/src/utils/core.js:62:28)
    at Function._call (file:///home/aelfwyne/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:1182:36)
Applying custom prompt post-processing of type semi_tools
Chat Completion request: {
  messages: [
    {
      role: 'system',
      content: '\n' +
        '\n' +
        '<summary>\n' +
        "2092-02-17 | 12:45: Ousef repairs armor with wood plates while discussing the mystery of ancient civilizations; a heavy thud and snapping branch in the canopy signal an imminen
```
