### ISSUE TITLE
[BUG] Using Impersonation in group chat breaks it and only one character can respond.

### ISSUE THREAD

**Issue by Berilium25** [SillyTavern/SillyTavern#266]
**Describe the bug**
When I use Impersonation on a group chat, the whole thing bugs out and only one character in the group responds, no matter if I select the other one to talk directly, if it's next on the list order or natural order.

**To Reproduce**
1. Create a group with any characters
2. Chat normally a few times to see how things work normally.
3. Try impersonation. I noticed that in the console it sends two system notes: One to answer as one of the characters, and the another one to respond as the user.
4. After that happens and I have the text of impersonation on tavern, only the character that was mentioned in the previous step on the console can respond and no other else. It also locks me into that chat group and can't select another chat, forcing me to reload the browser.

**Logs**

````
f-localStorage.js:8 LoadLocal -- SelectedNavTab
RossAscends-mods.js:118 Device type: desktop
f-localStorage.js:5 SaveLocal -- NavOpened : true
elevenlabs.js:44 Using default TTS Provider settings
elevenlabs.js:61 Settings loaded
f-localStorage.js:5 SaveLocal -- ActiveChar : null
f-localStorage.js:5 SaveLocal -- ActiveGroup : 1683626817886
RossAscends-mods.js:251 RA_TC -- no valid char found, closing.
index.js:250 getting sprites list
script.js:5055 confirmed del msgs, calling showswipesbtns
index.js:250 getting sprites list
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 2/3
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 879
openai.js:451 We're sending this:
openai.js:452 Array(12)
openai.js:453 Calculated the total context to be 1302 tokens
script.js:2567 entering chat update routine for non-swipe post
script.js:2581 entering chat update for groups
script.js:2280 /savechat called by /Generate
index.js:209 force redrawing character sprites list
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 3/4
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 1141
openai.js:451 We're sending this:
openai.js:452 Array(10)
openai.js:453 Calculated the total context to be 1361 tokens
script.js:2567 entering chat update routine for non-swipe post
script.js:2581 entering chat update for groups
script.js:2280 /savechat called by /Generate
index.js:209 force redrawing character sprites list
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 4/5
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 1078
openai.js:451 We're sending this:
openai.js:452 Array(12)
openai.js:453 Calculated the total context to be 1298 tokens
script.js:2280 /savechat called by /Generate
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 5/6
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 1304
openai.js:451 We're sending this:
openai.js:452 Array(12)
openai.js:453 Calculated the total context to be 1524 tokens
script.js:2567 entering chat update routine for non-swipe post
script.js:2581 entering chat update for groups
script.js:2280 /savechat called by /Generate
````

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Browser: Chrome
 - Generation API: OpenAi
 - Branch: dev
 - Model: whatever model Todd is, and claude slack

**Comment by Berilium25** [comment]
My bad, I continue fiddling with this and didn't realize I messed it up. I updated it now.

In regards of the bug, like I said before it sends two system notes: one for the character and one for the user.

![imagen](https://github.com/Cohee1207/SillyTavern/assets/26808493/3f567bbb-f41a-400a-ab1f-3b1ca59ca3c9)

Now, the looping bug. When I sent the impersonation request, I get the system notes as described above. Then, the bot replies in the console, even tough I requested an impersonation. And then at the end of the bot message it prompts those two system messages again: write as char and then write as user. And then the bot responds again in the console and it repeats the same system messages. Over and over.

Here is the log for that bug:

````
f-localStorage.js:8 LoadLocal -- SelectedNavTab
RossAscends-mods.js:118 Device type: desktop
f-localStorage.js:5 SaveLocal -- NavOpened : true
elevenlabs.js:44 Using default TTS Provider settings
elevenlabs.js:61 Settings loaded
f-localStorage.js:5 SaveLocal -- ActiveChar : null
f-localStorage.js:5 SaveLocal -- ActiveGroup : 1683626817886
RossAscends-mods.js:251 RA_TC -- no valid char found, closing.
index.js:250 getting sprites list
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 3/4
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 991
openai.js:451 We're sending this:
openai.js:452 Array(11)
openai.js:453 Calculated the total context to be 1211 tokens
script.js:2280 /savechat called by /Generate
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 3/4
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 991
openai.js:451 We're sending this:
openai.js:452 Array(11)
openai.js:453 Calculated the total context to be 1211 tokens
script.js:2280 /savechat called by /Generate
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 3/4
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 991
openai.js:451 We're sending this:
openai.js:452 Array(11)
openai.js:453 Calculated the total context to be 1211 tokens
script.js:2280 /savechat called by /Generate
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 3/4
script.js:1729 No WI, skipping chat2 for OAI
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:2128 rungenerate calling API
openai.js:422 991
openai.js:451 We're sending this:
openai.js:452 Array(11)
openai.js:453 Calculated the total context to be 1211 tokens
script.js:2298 undefined
script.js:2299 TypeError: Failed to fetch
    at sendOpenAIRequest (openai.js:543:28)
    at runGenerate (script.js:2138:21)
    at async Generate (script.js:1867:9)

````

Well, I had to close the console otherwise it would loop forever it seems. I don't know why it started looping, guess I'll continue fiddling with it.

**Comment by Berilium25** [comment]
I'm confused. That is not my JB prompt, I was not using any, that is the message that pops out in console when I push the impersonation button. It's all in it's default state.

And I get I you don't support slack and Todd, but like I said while the looping doesn't happen in Turbo the bug I described about  the chat locking up and others character not being able to respond still happens in Turbo aswell.

**Comment by Berilium25** [comment]
I tried it with pyg 6b on CPU mode and the group chat also locks up. It seems it also sends a line for the bot before the impersonation:

![imagen](https://github.com/Cohee1207/SillyTavern/assets/26808493/aee907c2-f561-4e28-8de2-94cd6cc1f7a1)

**Comment by RossAscends** [comment]
the bug with impersonation breaking group chats has been fixed. please reopen if you still have it.
