### ISSUE TITLE
[BUG] Error: Unsupported model type: whisper

### ISSUE THREAD

**Issue by gilbrotheraway** [SillyTavern/SillyTavern#2719]
### Environment

🪟 Windows

### System

w11

### Version

latest

### Describe the problem

when i select whisper Local on the web ui speech recognition settings i get this error

`Initializing transformers.js pipeline for task automatic-speech-recognition with model Xenova/whisper-small.en
Error: Unsupported model type: whisper
    at AutoModelForCTC.from_pretrained (file:///C:/Users/SillyTavern/SillyTavern-Launcher/SillyTavern/node_modules/sillytavern-transformers/src/models.js:5173:19)
    at async file:///C:/Users/SillyTavern/SillyTavern-Launcher/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:3099:33`

why is it do i need the Extras package?

### Additional info

Initializing transformers.js pipeline for task automatic-speech-recognition with model Xenova/whisper-small.en
Error: Unsupported model type: whisper
    at AutoModelForCTC.from_pretrained (file:///C:/Users/SillyTavern/SillyTavern-Launcher/SillyTavern/node_modules/sillytavern-transformers/src/models.js:5173:19)
    at async file:///C:/Users/SillyTavern/SillyTavern-Launcher/SillyTavern/node_modules/sillytavern-transformers/src/pipelines.js:3099:33

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not reproduced on my end. If you've used "node modules fix" from the launcher, it is likely resulted in installing a broken version of sillytavern-transformers. Update the launcher, perform `git reset --hard` to clean package-lock changes, then restart SillyTavern.
