### ISSUE TITLE
[BUG] <Importing error: Invalid string length>

### ISSUE THREAD

**Issue by watashi55** [SillyTavern/SillyTavern#3061]
### Environment

🪟 Windows

### System

Brave current

### Version

sillytavern@1.12.7
Running 'staging' (8da98faa9) - 2024-11-08 11:09:57 +0200
### Desktop Information

Node version: v22.2.0. Running in production environment.

### Describe the problem

When i try to import a card i have this error. I have over 9,660 cards so i don't know if that's the problem.

### Additional info

Found a chara_card_v2 character file.
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (B:\PygmalionAI\SillyTavern\node_modules\express\lib\response.js:1160:12)
    at ServerResponse.json (B:\PygmalionAI\SillyTavern\node_modules\express\lib\response.js:271:14)
    at ServerResponse.send (B:\PygmalionAI\SillyTavern\node_modules\express\lib\response.js:162:21)
    at file:///B:/PygmalionAI/SillyTavern/src/endpoints/characters.js:980:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Yeah, that may well be the case. Try not having too many.

**Comment by Petero48** [comment]
I am having the same issue, got it after starting adding more characters. Any way to fix that?

**Comment by watashi55** [comment]
its a limitation with the way chars are stored. a solution is apparently a vectorized database instead of a json. independently from what i can tell i think my import is bugged. ive never had {Never resize avatars} on and all my characters are at full size.

**Comment by SoraAndShiroe** [comment]
I have same issue and commenting to stay updated to this thread. I have tried both staging and releasing branch and replicated this error. Currently with 16,495 characters. a band aid fix is removing any characters that have any errors even little errors such as character field empty:tag,scenario,etc. then when you import new characters add them one by one and if same error pops up again remove that card.

**Comment by Wolfsblvt** [comment]
Pretty sure this should be fixed with the latest release **1.12.13** and the PR #3614.
Can you test and confirm?

**Comment by Cohee1207** [comment]
Here's a guide: https://docs.sillytavern.app/usage/faq/#when-i-import-a-lot-of-characters-the-app-becomes-slow-why

Enable lazy loading as it suggests, and you won't be having this issue anymore.
