### ISSUE TITLE
[BUG] Get error when generating images using localhost ComfyUI

### ISSUE THREAD

**Issue by Sunsetra** [SillyTavern/SillyTavern#3064]
### Environment

🪟 Windows

### System

Edge 130

### Version

1.12.7

### Desktop Information

- Node version: v22.2.0
- Generation API: localhost comfyui
- Branch: staging
- Model: sdxl

### Describe the problem

I have configured the local ComfyUI URL, workflow, and related parameters in SillyTavern, and I can successfully connect to ComfyUI.

![203718](https://github.com/user-attachments/assets/b067698d-cb48-44a9-ad67-3a3509c92557)![203658](https://github.com/user-attachments/assets/03cf20fc-183f-4b3f-a801-608cec5ed8ca)

Then I tried to type `/sd apple` command in chat, the comfyui generated an image normally.
But after the image generated, SillyTavern returned **Image Generation failed error** instead of show the image.

![204806](https://github.com/user-attachments/assets/73934a9e-5636-4344-9ea9-8205dcb931f6)

I checked the output folder of comfyui and ensure the image has successfully generated, and the comfyui console returns no error.
![204455](https://github.com/user-attachments/assets/16d31d52-e2f1-441a-8357-8c7a9fa28bea)

### Additional info

SillyTavern Console:
```
TypeError: Cannot read properties of undefined (reading 'filename')
    at file:///C:/Tools/SillyTavern/src/endpoints/stable-diffusion.js:558:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Browser Console:
```
script.js:3420 Generate entered
index.js:2306 Generation mode 6 triggered with apple
index.js:2343 Processed image prompt: apple
index.js:3262 [...the very long workflow...]
:41476/api/sd/comfy/generate:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:2639  Error: Internal Server Error
    at generateComfyImage (index.js:3278:15)
    at async sendGenerationRequest (index.js:2616:26)
    at async generatePicture (index.js:2352:21)
    at async SlashCommand.callback (index.js:3920:24)
    at async SlashCommandClosure.executeStep (SlashCommandClosure.js:339:39)
    at async SlashCommandClosure.executeDirect (SlashCommandClosure.js:261:20)
    at async SlashCommandClosure.execute (SlashCommandClosure.js:149:20)
    at async executeSlashCommandsWithOptions (slash-commands.js:4186:24)
    at async executeSlashCommandsOnChatInput (slash-commands.js:4083:18)
    at async processCommands (script.js:2684:5)
sendGenerationRequest @ index.js:2639
SlashCommandClosure.js:528  /imagine returned undefined or null. Auto-fixing to empty string.
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Works for me (latest Comfy pull).
Can you share your workflow?

**Comment by Sunsetra** [comment]
I have updated comfy to latest pull, but still get same error.
This is my workflow.
<details><summary>Workflow</summary>

```json
{
  "131": {
    "inputs": {
      "ckpt_name": "%model%"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "134": {
    "inputs": {
      "width": [
        "149",
        0
      ],
      "height": [
        "152",
        0
      ],
      "crop_w": 0,
      "crop_h": 0,
      "target_width": [
        "149",
        0
      ],
      "target_height": [
        "152",
        0
      ],
      "text_g": [
        "174",
        0
      ],
      "text_l": [
        "174",
        0
      ],
      "clip": [
        "131",
        1
      ]
    },
    "class_type": "CLIPTextEncodeSDXL",
    "_meta": {
      "title": "CLIPTextEncodeSDXL"
    }
  },
  "138": {
    "inputs": {
      "add_noise": true,
      "noise_seed": "%seed%",
      "cfg": 7,
      "model": [
        "182",
        0
      ],
      "positive": [
        "134",
        0
      ],
      "negative": [
        "172",
        0
      ],
      "sampler": [
        "140",
        0
      ],
      "sigmas": [
        "141",
        0
      ],
      "latent_image": [
        "139",
        0
      ]
    },
    "class_type": "SamplerCustom",
    "_meta": {
      "title": "SamplerCustom"
    }
  },
  "139": {
    "inputs": {
      "width": "%width%",
      "height": "%height%",
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "140": {
    "inputs": {
      "sampler_name": "%sampler%"
    },
    "class_type": "KSamplerSelect",
    "_meta": {
      "title": "KSamplerSelect"
    }
  },
  "141": {
    "inputs": {
      "scheduler": "%scheduler%",
      "steps": "%steps%",
      "denoise": 1,
      "model": [
        "131",
        0
      ]
    },
    "class_type": "BasicScheduler",
    "_meta": {
      "title": "BasicScheduler"
    }
  },
  "142": {
    "inputs": {
      "samples": [
        "138",
        1
      ],
      "vae": [
        "131",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "149": {
    "inputs": {
      "expression": "a.width * 2",
      "a": [
        "139",
        0
      ]
    },
    "class_type": "MathExpression|pysssss",
    "_meta": {
      "title": "Math Expression 🐍"
    }
  },
  "152": {
    "inputs": {
      "expression": "a.height * 2",
      "a": [
        "139",
        0
      ]
    },
    "class_type": "MathExpression|pysssss",
    "_meta": {
      "title": "Math Expression 🐍"
    }
  },
  "162": {
    "inputs": {
      "action": "append",
      "tidy_tags": "yes",
      "text_a": "low quality,worst quality",
      "text_b": [
        "197",
        0
      ]
    },
    "class_type": "StringFunction|pysssss",
    "_meta": {
      "title": "String Function 🐍"
    }
  },
  "172": {
    "inputs": {
      "width": [
        "149",
        0
      ],
      "height": [
        "152",
        0
      ],
      "crop_w": 0,
      "crop_h": 0,
      "target_width": [
        "149",
        0
      ],
      "target_height": [
        "152",
        0
      ],
      "text_g": [
        "162",
        0
      ],
      "text_l": [
        "162",
        0
      ],
      "clip": [
        "131",
        1
      ]
    },
    "class_type": "CLIPTextEncodeSDXL",
    "_meta": {
      "title": "CLIPTextEncodeSDXL"
    }
  },
  "174": {
    "inputs": {
      "positive": "%prompt%",
      "打开可视化PromptUI": ""
    },
    "class_type": "WeiLinComfyUIPromptAllInOneGreat",
    "_meta": {
      "title": "WeiLin 正向提示词转String"
    }
  },
  "182": {
    "inputs": {
      "input_block": true,
      "middle_block": true,
      "output_block": true,
      "multiscale_mode": "Default",
      "multiscale_strength": 1,
      "slice_b1": 640,
      "slice_b2": 320,
      "b1": 1.3,
      "b2": 1.4000000000000001,
      "s1": 0.9,
      "s2": 0.2,
      "threshold": 1,
      "use_override_scales": "false",
      "override_scales": "# OVERRIDE SCALES\n\n# Sharpen\n# 10, 1.5",
      "model": [
        "131",
        0
      ]
    },
    "class_type": "FreeU_V2 (Advanced)",
    "_meta": {
      "title": "FreeU V2 (Advanced Plus)"
    }
  },
  "197": {
    "inputs": {
      "string": "embedding:unaestheticXL_hk1"
    },
    "class_type": "Primitive string multiline [Crystools]",
    "_meta": {
      "title": "🪛 Primitive string multiline"
    }
  },
  "207": {
    "inputs": {
      "filename_prefix": "SillyTavern",
      "images": [
        "142",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  }
}
```
</details>

**Comment by Sunsetra** [comment]
> Works for me (latest Comfy pull).
> Can you share your workflow?

I have updated comfy to latest pull, but still get same error.
This is my workflow.
<details><summary>Workflow</summary>

```json
{
  "131": {
    "inputs": {
      "ckpt_name": "%model%"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "134": {
    "inputs": {
      "width": [
        "149",
        0
      ],
      "height": [
        "152",
        0
      ],
      "crop_w": 0,
      "crop_h": 0,
      "target_width": [
        "149",
        0
      ],
      "target_height": [
        "152",
        0
      ],
      "text_g": [
        "174",
        0
      ],
      "text_l": [
        "174",
        0
      ],
      "clip": [
        "131",
        1
      ]
    },
    "class_type": "CLIPTextEncodeSDXL",
    "_meta": {
      "title": "CLIPTextEncodeSDXL"
    }
  },
  "138": {
    "inputs": {
      "add_noise": true,
      "noise_seed": "%seed%",
      "cfg": 7,
      "model": [
        "182",
        0
      ],
      "positive": [
        "134",
        0
      ],
      "negative": [
        "172",
        0
      ],
      "sampler": [
        "140",
        0
      ],
      "sigmas": [
        "141",
        0
      ],
      "latent_image": [
        "139",
        0
      ]
    },
    "class_type": "SamplerCustom",
    "_meta": {
      "title": "SamplerCustom"
    }
  },
  "139": {
    "inputs": {
      "width": "%width%",
      "height": "%height%",
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "140": {
    "inputs": {
      "sampler_name": "%sampler%"
    },
    "class_type": "KSamplerSelect",
    "_meta": {
      "title": "KSamplerSelect"
    }
  },
  "141": {
    "inputs": {
      "scheduler": "%scheduler%",
      "steps": "%steps%",
      "denoise": 1,
      "model": [
        "131",
        0
      ]
    },
    "class_type": "BasicScheduler",
    "_meta": {
      "title": "BasicScheduler"
    }
  },
  "142": {
    "inputs": {
      "samples": [
        "138",
        1
      ],
      "vae": [
        "131",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "149": {
    "inputs": {
      "expression": "a.width * 2",
      "a": [
        "139",
        0
      ]
    },
    "class_type": "MathExpression|pysssss",
    "_meta": {
      "title": "Math Expression 🐍"
    }
  },
  "152": {
    "inputs": {
      "expression": "a.height * 2",
      "a": [
        "139",
        0
      ]
    },
    "class_type": "MathExpression|pysssss",
    "_meta": {
      "title": "Math Expression 🐍"
    }
  },
  "162": {
    "inputs": {
      "action": "append",
      "tidy_tags": "yes",
      "text_a": "low quality,worst quality",
      "text_b": [
        "197",
        0
      ]
    },
    "class_type": "StringFunction|pysssss",
    "_meta": {
      "title": "String Function 🐍"
    }
  },
  "172": {
    "inputs": {
      "width": [
        "149",
        0
      ],
      "height": [
        "152",
        0
      ],
      "crop_w": 0,
      "crop_h": 0,
      "target_width": [
        "149",
        0
      ],
      "target_height": [
        "152",
        0
      ],
      "text_g": [
        "162",
        0
      ],
      "text_l": [
        "162",
        0
      ],
      "clip": [
        "131",
        1
      ]
    },
    "class_type": "CLIPTextEncodeSDXL",
    "_meta": {
      "title": "CLIPTextEncodeSDXL"
    }
  },
  "174": {
    "inputs": {
      "positive": "%prompt%",
      "打开可视化PromptUI": ""
    },
    "class_type": "WeiLinComfyUIPromptAllInOneGreat",
    "_meta": {
      "title": "WeiLin 正向提示词转String"
    }
  },
  "182": {
    "inputs": {
      "input_block": true,
      "middle_block": true,
      "output_block": true,
      "multiscale_mode": "Default",
      "multiscale_strength": 1,
      "slice_b1": 640,
      "slice_b2": 320,
      "b1": 1.3,
      "b2": 1.4000000000000001,
      "s1": 0.9,
      "s2": 0.2,
      "threshold": 1,
      "use_override_scales": "false",
      "override_scales": "# OVERRIDE SCALES\n\n# Sharpen\n# 10, 1.5",
      "model": [
        "131",
        0
      ]
    },
    "class_type": "FreeU_V2 (Advanced)",
    "_meta": {
      "title": "FreeU V2 (Advanced Plus)"
    }
  },
  "197": {
    "inputs": {
      "string": "embedding:unaestheticXL_hk1"
    },
    "class_type": "Primitive string multiline [Crystools]",
    "_meta": {
      "title": "🪛 Primitive string multiline"
    }
  },
  "207": {
    "inputs": {
      "filename_prefix": "SillyTavern",
      "images": [
        "142",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  }
}
```
</details>

**Comment by Sunsetra** [comment]
I got it, one of the addons caused the error. I deleted the addon and the error gone.

**Comment by sean908** [comment]
> I got it, one of the addons caused the error. I deleted the addon and the error gone.

Bro, how did you find out it was an add-on problem?
