### ISSUE TITLE
[BUG] Must use import to load ES Module

### ISSUE THREAD

**Issue by YandreTheDrone** [SillyTavern/SillyTavern#3123]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.12.7

### Desktop Information

Node: v12.16.1

### Describe the problem

First time using/running SillyTavern, having cloned the git (release branch) as per instructions - when I press start.bat it gives me an error

### Additional info

> Below is the what comes up in start.bat

sillytavern@1.12.7 postinstall H:\SillyTavern
node post-install.js

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: H:\SillyTavern\post-install.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sillytavern@1.12.7 postinstall: `node post-install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sillytavern@1.12.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[REDACTED]\AppData\Roaming\npm-cache\_logs\2024-11-29T09_28_44_951Z-debug.log
internal/
[2024-11-29T09_28_44_951Z-debug.log](https://github.com/user-attachments/files/17957166/2024-11-29T09_28_44_951Z-debug.log)
modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: H:\SillyTavern\server.js
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)←[39m
←[90m    at internal/main/run_main_module.js:18:47←[39m {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m

> below is the log it mentions above
[2024-11-29T09_28_44_951Z-debug.log](https://github.com/user-attachments/files/17957166/2024-11-29T09_28_44_951Z-debug.log)
### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Delete `node_modules` folder, run `npm cache clean --force` in cmd, restart from `start.bat`.
