### ISSUE TITLE
[BUG] ERROR in ./public/lib.js

### ISSUE THREAD

**Issue by VoidEmpty** [SillyTavern/SillyTavern#3138]
### Environment

🪟 Windows

### System

Windows 11

### Version

1.12.8

### Desktop Information

Node.js version: v23.2.0
Generation API: Ollama
Branch: staging

### Describe the problem

Can't start the server after 1.12.8 update:

ERROR in ./public/lib.js + 61 modules
Unexpected end of JSON input
![{D7FA9A7A-9F44-49F8-951A-0B0542ACB94C}](https://github.com/user-attachments/assets/21606bcb-3314-44fa-9d28-f00de27b89eb)

### Additional info

Tried everything, nothing fixed the issue.
https://docs.sillytavern.app/installation/updating/#there-are-unresolved-conflicts-in-the-working-directory

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Clear npm cache first by running `npm cache clean --force` and remove `node_modules` directory, then try restarting with start.bat.
If that didn't work, open `webpack.config.js` in a text editor and change `stats.preset` from `minimal` to `detailed`, then send here the output after restarting.

**Comment by VoidEmpty** [comment]
```
Using data root: ./data


SillyTavern 1.12.8
Running 'release' (ce34f14f1) - 2024-12-01 17:41:37 +0200


Compiling frontend libraries...
PublicPath: auto
Entrypoint main = lib.js
chunk {792} (runtime: main) lib.js (main) 3.95 MiB (javascript) 557 bytes (runtime) [entry]
  > ./public/lib.js  main

LOG from webpack.Compilation
    385 modules hashed, 0 from cache (0.86 variants per module in average)
    0% code generated (1 generated, 384 from cache)
    0% code generated (0 generated, 5 from cache)
+ 25 hidden lines

LOG from webpack.ResolverCachePlugin
    0% really resolved (0 real resolves with 0 cached but invalid, 763 cached valid, 0 concurrent)

LOG from webpack.FlagDependencyExportsPlugin
    2% of exports of modules have been determined (372 no declared exports, 7 not cached, 1 flagged uncacheable, 66 from cache, 0 from mem cache, 4 additional calculations due to dependencies)
+ 3 hidden lines

LOG from webpack.buildChunkGraph
    899 queue items processed (446 blocks)
    0 chunk groups connected
    0 chunk groups processed for merging (0 module sets, 0 forked, 0 + 0 modules forked, 0 + 0 modules merged into fork, 0 resulting modules)
    0 chunk group info updated (0 already connected chunk groups reconnected)
+ 5 hidden lines

LOG from webpack.FileSystemInfo
    0 new snapshots created
    89% root snapshot uncached (1080 / 1208)
    1% children snapshot uncached (13 / 1296)
    1925 entries tested
    File info in cache: 14 timestamps 0 hashes 0 timestamp hash combinations
    Directory info in cache: 0 timestamps 0 hashes 0 timestamp hash combinations
    Managed items info in cache: 73 items

ERROR in ./public/lib.js + 61 modules
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConcatenationScope.matchModuleReference (D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\ConcatenationScope.js:145:13)
    at ConcatenatedModule.codeGeneration (D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\optimize\ConcatenatedModule.js:1253:41)
    at D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\Compilation.js:3492:22
    at D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\Cache.js:89:6
    at D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\Cache.js:43:10
    at D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\cache\IdleFileCachePlugin.js:78:9
    at D:\Programs\Tavern\SillyTavern\node_modules\webpack\lib\Cache.js:92:6
    at eval (eval at create (D:\Programs\Tavern\SillyTavern\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

2024-12-02 11:35:50: webpack 5.95.0 compiled with 1 error in 305 ms (874b45e2c0a7c5ef741f)

Launching...
SillyTavern is listening on IPv4: 0.0.0.0:8000

=================================================

Go to: http://127.0.0.1:8000/ to open SillyTavern

=================================================
```

**Comment by Cohee1207** [comment]
Thanks. This appears to be a Node.js runtime issue. Upgrade to at least Node 23.3.0 or use the latest LTS version

https://github.com/webpack/webpack/issues/18963#issuecomment-2491295560

**Comment by VoidEmpty** [comment]
Yes, it works now. But it's better to mention it in the changelog.

**Comment by Huaian666** [comment]
can reproduce this consistently. happens when the input is empty or whitespace only
