### ISSUE TITLE
[BUG] <title> Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx TypeError: fetch failed

### ISSUE THREAD

**Issue by LostS1ght** [SillyTavern/SillyTavern#3203]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.12.5

### Describe the problem

local classify cannot run

### Additional info

Classify input: You wake with a start, recalling the events that led you deep into the forest and the beasts that assailed you. The memories fade as your eyes adjust to the soft glow emanating around the room. Ah, you're awake at last. I hope the tea helps restore your strength. Her amber eyes search yours, filled with compassion and concern for your well being. Please, rest. You're safe here. I'll look after you, but you need to rest. My magic can only do so much to heal you.
Initializing transformers.js pipeline for task text-classification with model Cohee/distilbert-base-uncased-go-emotions-onnx
TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async getModelFile (file:///K:/AI/SillyTavern-1.12.5/node_modules/sillytavern-transformers/src/utils/hub.js:471:24)
    at async constructSession (file:///K:/AI/SillyTavern-1.12.5/node_modules/sillytavern-transformers/src/models.js:123:18)
    at async Promise.all (index 1)
    at async DistilBertForSequenceClassification.from_pretrained (file:///K:/AI/SillyTavern-1.12.5/node_modules/sillytavern-transformers/src/models.js:793:20)
    at async AutoModelForSequenceClassification.from_pretrained (file:///K:/AI/SillyTavern-1.12.5/node_modules/sillytavern-transformers/src/models.js:5166:20)
    at async Promise.all (index 1)
    at async loadItems (file:///K:/AI/SillyTavern-1.12.5/node_modules/sillytavern-transformers/src/pipelines.js:3116:5)
    at async pipeline (file:///K:/AI/SillyTavern-1.12.5/node_modules/sillytavern-transformers/src/pipelines.js:3056:21) {
  [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: huggingface.co:443, timeout: 10000ms)
      at onConnectTimeout (node:internal/deps/undici/undici:2602:28)
      at Immediate._onImmediate (node:internal/deps/undici/undici:2568:35)
      at process.processImmediate (node:internal/timers:491:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LostS1ght** [comment]
the model files had already put in: data/_cache/Cohee/distilbert-base-uncased-go-emotions-onnx

**Comment by Cohee1207** [comment]
Check that huggingface.co host is available from your machine. Remove the cached model files and let it redownload.

**Comment by LostS1ght** [comment]
I redownloaded all the model files, and the problem solved. Thank u very much!
