### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Punderful20** [SillyTavern/SillyTavern#430]
**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
TypeError or Async when attempting to use Kobold Horde.

**To Reproduce**
1. Send message while using Kobold Horde as API.

**Expected behavior**
User expected a message to be produced by Kobold Horde.

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/52357027/dc1092e5-b9f5-4d96-97c1-3238e0144619)

**Logs**
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11522:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async postAsync (C:\Users\igorh\OneDrive\Documentos\GitHub\SillyTavern\server.js:2687:22)
    at async C:\Users\igorh\OneDrive\Documentos\GitHub\SillyTavern\server.js:2922:22 {
  cause: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
      at new NodeError (node:internal/errors:399:5)
      at internalConnectMultiple (node:net:1099:20)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_SOCKET_CONNECTION_TIMEOUT'
  }
}

**Desktop (please complete the following information):**
 - OS/Device: [e.g. Windows 11]
 - Environment: [cloud, local]
 - Node.js version: 20.2.0
 - Browser: Firefox, OperaGX
 - Generation API: Kobold Horde
 - Branch: Main
 - Model: Any

**Additional context**
This report was created on behalf of a user who has this problem. I do not have this problem myself.

**Comment by ntvm** [comment]
I also have that issue, what appeared after update from 1.6.0 to higher tavern. With that, problem, appeared another. Tavern did not recive some incoming texts
![image](https://github.com/SillyTavern/SillyTavern/assets/134743763/c4aa6f7f-2d3c-43ab-a842-48a24251dea4)
![image](https://github.com/SillyTavern/SillyTavern/assets/134743763/65e648c5-0190-4464-8d34-7ef1c9ba5d2f)

**Comment by Punderful20** [comment]
The user attempted to solve the issue using the suggestions above, but the problem still persists. However, the error produced is now the following:
(node:4040) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use sillytavern-win --trace-warnings ... to show where the warning was created)
Error: [object Response]
    at postAsync (C:\snapshot\SillyTavern\server.js:2694:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\snapshot\SillyTavern\server.js:2922:22

**Comment by CarlXx621** [comment]
> Node 20 has problems with networking due to its internal bugs. We advise our users to stay on the Node LTS version (which is 18). Let your user try installing Node 18. Alternatively, they could download the Windows binary from the continuous release and drop it into their install folder, running that instead of start.bat: https://github.com/SillyTavern/SillyTavern/releases/tag/ci-main

How to install node 18 in termux?
