### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by feliscat** [SillyTavern/SillyTavern#434]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Building docker with docker compose produces an image that errors

**To Reproduce**
```shell
git clone https://github.com/SillyTavern/SillyTavern.git
cd SillyTavern/build
docker compose build
cd ..
cp docker/docker-compose.yml ./
docker compose up -d
``` 

**Expected behavior**
sillytavern to start on port 8000

**Screenshots**
n/a

**Logs**

'''sillytavern  | Node.js v19.1.0
sillytavern  | Resource not found, copying from defaults: groups
sillytavern  | cp: can't stat 'public/groups.default': No such file or directory
sillytavern  | Resource not found, copying from defaults: group chats
sillytavern  | cp: can't stat 'public/group chats.default': No such file or directory
sillytavern  | Running from source
sillytavern  | node:fs:1388
sillytavern  |   handleErrorFromBinding(ctx);
sillytavern  |   ^
sillytavern  | 
sillytavern  | Error: ENOENT: no such file or directory, mkdir 'public/worlds/'
sillytavern  |     at Object.mkdirSync (node:fs:1388:3)
sillytavern  |     at ensurePublicDirectoriesExist (/home/node/app/server.js:2808:16)
sillytavern  |     at Server.setupTasks (/home/node/app/server.js:2723:5)
sillytavern  |     at Object.onceWrapper (node:events:627:28)
sillytavern  |     at Server.emit (node:events:513:28)
sillytavern  |     at emitListeningNT (node:net:1502:10)
sillytavern  |     at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
sillytavern  |   errno: -2,
sillytavern  |   syscall: 'mkdir',
sillytavern  |   code: 'ENOENT',
sillytavern  |   path: 'public/worlds/'
sillytavern  | }
'''

**Desktop (please complete the following information):**
 - OS/Device: Docker on Ubuntu 20.04

**Comment by feliscat** [comment]
To fix this, I had to create 'group' and 'group chats' folders in public/ before building the image.

**Comment by feliscat** [comment]
Fixed.  Thank you!

**Comment by FilJed** [comment]
It seems that several things have changed since this issue was opened. Currently, I'm unable to build and run SillyTavern using Docker. Are there any instructions available for that?

**Comment by Cohee1207** [comment]
I don't use Docker myself, so can't provide any meaningful guidance. There's a prebuilt image however:

https://github.com/SillyTavern/SillyTavern/pkgs/container/sillytavern

**Comment by iieedndb** [comment]
2024-01-01 21:25:31 Running from source
2024-01-01 21:25:31 SillyTavern 1.11.1
2024-01-01 21:25:31 node:fs:1388
2024-01-01 21:25:31   handleErrorFromBinding(ctx);
2024-01-01 21:25:31   ^
2024-01-01 21:25:31 
2024-01-01 21:25:31 Error: ENOENT: no such file or directory, mkdir 'public/user/images/'
2024-01-01 21:25:31     at Object.mkdirSync (node:fs:1388:3)
2024-01-01 21:25:31     at ensurePublicDirectoriesExist (/home/node/app/server.js:689:16)
2024-01-01 21:25:31     at Server.setupTasks (/home/node/app/server.js:603:5)
2024-01-01 21:25:31     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-01-01 21:25:31   errno: -2,
2024-01-01 21:25:31   syscall: 'mkdir',
2024-01-01 21:25:31   code: 'ENOENT',
2024-01-01 21:25:31   path: 'public/user/images/'
2024-01-01 21:25:31 }
2024-01-01 21:25:31 
2024-01-01 21:25:31 Node.js v19.1.0


can we please add placeholder for /user/ folder?
