### ISSUE TITLE
[BUG] Poe API Expire or Invalid

### ISSUE THREAD

**Issue by ToyotaPrius2008Diesel** [SillyTavern/SillyTavern#458]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
The Poe API invalid or expired

**To Reproduce**
1. Launch SillyTavern
2. Try to connect to Poe API
3. See "Invalid or expired token" on top right corner

**Expected behavior**
Connect to Poe API
**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/102476450/bd95c8fd-3dd6-416c-88c4-2cdce58c8cce)

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

Downloading next_data...
Downloading channel data...
TypeError: Cannot read properties of undefined (reading 'filter')
    at Client.get_bots (C:\Users\User\Desktop\SillyTavern-1.6.6\poe-client.js:324:35)
    at Client.init (C:\Users\User\Desktop\SillyTavern-1.6.6\poe-client.js:290:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getPoeClient (C:\Users\User\Desktop\SillyTavern-1.6.6\server.js:2097:5)
    at async C:\Users\User\Desktop\SillyTavern-1.6.6\server.js:2109:24
Downloading next_data...
Downloading channel data...
TypeError: Cannot read properties of undefined (reading 'filter')
    at Client.get_bots (C:\Users\User\Desktop\SillyTavern-1.6.6\poe-client.js:324:35)
    at Client.init (C:\Users\User\Desktop\SillyTavern-1.6.6\poe-client.js:290:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getPoeClient (C:\Users\User\Desktop\SillyTavern-1.6.6\server.js:2097:5)
    at async C:\Users\User\Desktop\SillyTavern-1.6.6\server.js:2109:24
Downloading next_data...
Downloading channel data...
TypeError: Cannot read properties of undefined (reading 'filter')
    at Client.get_bots (C:\Users\User\Desktop\SillyTavern-1.6.6\poe-client.js:324:35)
    at Client.init (C:\Users\User\Desktop\SillyTavern-1.6.6\poe-client.js:290:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getPoeClient (C:\Users\User\Desktop\SillyTavern-1.6.6\server.js:2097:5)
    at async C:\Users\User\Desktop\SillyTavern-1.6.6\server.js:2109:24
    
**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: Local
 - Node.js version (if applicable): Node.js v18.16.0.
 - Browser: Chrome
 - Generation API: Poe
 - Branc: [main]
 - Model: ChatGPT

**Comment by thePhantom2** [comment]
So what to do now?

**Comment by ToyotaPrius2008Diesel** [comment]
> Yes, Poe broke again. Git pull and it will be okay.

How? I

**Comment by ToyotaPrius2008Diesel** [comment]
> Yes, Poe broke again. Git pull and it will be okay.

How exactly? I'm not familiar with coding, I managed to get Tavern running from a guide.

**Comment by uadies** [comment]
I have no idea what to do
