### ISSUE TITLE
[BUG] POE Issue since POE issue

### ISSUE THREAD

**Issue by thib5** [SillyTavern/SillyTavern#488]
hi, since the issue with poe and the token and everything i can make poe work. i did all the update. the api seams connected but when i chat with a character it anser nothing and in my consol it said :

[Your the next response shall only be written from the point of view of Nat. Do not seek approval of your writing style at the end of the response.]
ReferenceError: data is not defined
    at Client.send_query (/Users/USER/Documents/s/.SillyTavern/poe-client.js:384:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.send_message (/Users/USER/Documents/s/.SillyTavern/poe-client.js:524:29)
    at async /Users/thib5/Documents/s/.SillyTavern/server.js:2187:30

Thanks

**Comment by eblan333** [comment]
same shit, but mine just typed ...
when im starts typing with less ~ symbols, problem get fixed

**Comment by thib5** [comment]
with less symbols ?
