### ISSUE TITLE
[BUG] No response with Oobabooga 1-click installer on Windows 10

### ISSUE THREAD

**Issue by Asais10** [SillyTavern/SillyTavern#56]
**Describe the bug**
SillyTavern correctly boots up, but the characters refuse to respond.

**To Reproduce**
1. Install oobabooga 1-click-install text generation webui (and nodejs and sillytavern)
2. edit "start-webui.bat" to "call python server.py --load-in-8bit --model pygmalion-6b --no-stream --extensions api"
4. Launch oobabooga, if you test it by itself (against the default notebook bot), it works normally 
5. Try using SillyTavern, no response

**Expected behavior**
It should reply

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Browser: Brave (Chromium-based)
 - Generation API: Oobabooga
 - Branch: main
 - Model: Pygmalion 6b (default release, not dev nor first build)

**Additional context**
Error log on oobabooga side:

127.0.0.1 - - [11/Apr/2023 22:14:00] "GET /api/v1/model HTTP/1.1" 200 -                                                 127.0.0.1 - - [11/Apr/2023 22:14:00] code 404, message Not Found                                                        127.0.0.1 - - [11/Apr/2023 22:14:00] "GET /api/v1/config/soft_prompts_list HTTP/1.1" 404 -                              Traceback (most recent call last):                                                                                        File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict                                                                                                                        output = await app.get_blocks().process_api(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api                                                                                                                       result = await self.call_function(                                                                                    File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function                                                                                                                      prediction = await anyio.to_thread.run_sync(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync                                                                                                                          return await get_asynclib().run_sync_in_worker_thread(                                                                File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread                                                                                               return await future                                                                                                   File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run                                                                                                                     result = context.run(func, *args)                                                                                     File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration                                                                                                                     return next(iterator)                                                                                                 File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\api.py", line 28, in generate_reply_wrapper        for i in generate_reply(params[0], generate_params):                                                                  File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 167, in generate_reply                                                                                                                           input_ids = encode(question, generate_state['max_new_tokens'], add_bos_token=generate_state['add_bos_token'])       KeyError: 'add_bos_token'

Error log on SillyTavern side:

#### { error: null } 

Another notable thing is that previously I ran oobabooga using the same settings on WSL2, and SillyTavern worked fine, but now I tried switching to Windows 10 running directly and it broke.

**Comment by Asais10** [comment]
Well it still seems broken, just the oobabooga side of the log says something different

                                                             Traceback (most recent call last):                                                                                        File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict                                                                                                                        output = await app.get_blocks().process_api(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api                                                                                                                       result = await self.call_function(                                                                                    File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function                                                                                                                      prediction = await anyio.to_thread.run_sync(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync                                                                                                                          return await get_asynclib().run_sync_in_worker_thread(                                                                File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread                                                                                               return await future                                                                                                   File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run                                                                                                                     result = context.run(func, *args)                                                                                     File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration                                                                                                                     return next(iterator)                                                                                                 File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\api.py", line 28, in generate_reply_wrapper        for i in generate_reply(params[0], generate_params):                                                                  File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply                                                                                                                           input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))    File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 19, in get_max_prompt_length                                                                                                                     max_length = state['truncation_length'] - state['max_new_tokens']                                                   KeyError: 'truncation_length'

**Comment by Asais10** [comment]
Still broken, different error on oobabooga side though. I updated both oobabooga and sillytavern

Traceback (most recent call last):                                                                                        File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict                                                                                                                        output = await app.get_blocks().process_api(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api                                                                                                                       result = await self.call_function(                                                                                    File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function                                                                                                                      prediction = await anyio.to_thread.run_sync(                                                                          File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync                                                                                                                          return await get_asynclib().run_sync_in_worker_thread(                                                                File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread                                                                                               return await future                                                                                                   File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run                                                                                                                     result = context.run(func, *args)                                                                                     File "C:\Program Files\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration                                                                                                                     return next(iterator)                                                                                                 File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\api.py", line 28, in generate_reply_wrapper        for i in generate_reply(params[0], generate_params):                                                                  File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply                                                                                                                           input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))    File "C:\Program Files\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 19, in get_max_prompt_length                                                                                                                     max_length = state['truncation_length'] - state['max_new_tokens']                                                   KeyError: 'truncation_length'

**Comment by Asais10** [comment]
Any way to roll back to the slightly earlier version of oobabooga?
