### ISSUE TITLE
[BUG] Poe doesn't clear context when regenerating responses.

### ISSUE THREAD

**Issue by 0mniSci** [SillyTavern/SillyTavern#674]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Whenever you press "Regenerate" it usually clears the context of the previous chat on Poe, but recently it doesn't clear context, which makes regenerating responses useless because it gives you the almost the exact same response as before. This happens with every model, even Claude and ChatGPT.

**To Reproduce**
1. Go to SillyTavern
2. Click on Regenerate
3. See error

**Expected behavior**
When you click 'Regenerate" it should clear context from the previous response on Poe, which would give you a completely different, unique response each time.

**Logs**

Purging messages from capybara
Downloading 50 messages from capybara
Error on request attempt 1
Error on request attempt 2
Error on request attempt 3
Error on request attempt 4
Error on request attempt 5
Error on request attempt 6
Error on request attempt 7
Error on request attempt 8
Error on request attempt 9
Error on request attempt 10
Error: Failed to download  too many times.
    at request_with_retries (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:287:11)
    at async Client.send_query (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:541:23)
    at async Client.get_message_history (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:801:24)
    at async Client.purge_conversation (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:821:30)
    at async C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\server.js:2525:13
Websocket ping timed out.
WebSocket died. Reconnecting...
Downloading next_data...
Downloading channel data...
'viewer' key: props.pageProps.data.viewer
'chatOfBotHandle' key: props.pageProps.data.chatOfBotHandle
'defaultBotNickname' key: props.pageProps.data.chatOfBotHandle.defaultBotNickname
Downloading Sage
Downloading GPT-4
Downloading Claude+
Downloading Claude-instant-100k
Downloading Claude-instant
Downloading ChatGPT
Downloading Google-PaLM
Subscribing to mutations
Error on request attempt 1
Error on request attempt 2
Error on request attempt 3
Error on request attempt 4
Error on request attempt 5
Client initialized.

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version: v19.6.0
 - Browser: Chrome
 - Generation API: Poe
 - Branch: dev (Same bug occurs with main)
 - Model: Sage (Happens with every model)

**Additional context**
Have tried using the main branch, using different models, closing and reopening SillyTavern, still happens.

**Comment by Pavelgon4ik** [comment]
> **Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?** Yes
> 
> **Describe the bug** Whenever you press "Regenerate" it usually clears the context of the previous chat on Poe, but recently it doesn't clear context, which makes regenerating responses useless because it gives you the almost the exact same response as before. This happens with every model, even Claude and ChatGPT.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to SillyTavern
> 2. Click on Regenerate
> 3. See error
> 
> **Expected behavior** When you click 'Regenerate" it should clear context from the previous response on Poe, which would give you a completely different, unique response each time.
> 
> **Logs**
> 
> Purging messages from capybara Downloading 50 messages from capybara Error on request attempt 1 Error on request attempt 2 Error on request attempt 3 Error on request attempt 4 Error on request attempt 5 Error on request attempt 6 Error on request attempt 7 Error on request attempt 8 Error on request attempt 9 Error on request attempt 10 Error: Failed to download too many times. at request_with_retries (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:287:11) at async Client.send_query (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:541:23) at async Client.get_message_history (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:801:24) at async Client.purge_conversation (C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:821:30) at async C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\server.js:2525:13 Websocket ping timed out. WebSocket died. Reconnecting... Downloading next_data... Downloading channel data... 'viewer' key: props.pageProps.data.viewer 'chatOfBotHandle' key: props.pageProps.data.chatOfBotHandle 'defaultBotNickname' key: props.pageProps.data.chatOfBotHandle.defaultBotNickname Downloading Sage Downloading GPT-4 Downloading Claude+ Downloading Claude-instant-100k Downloading Claude-instant Downloading ChatGPT Downloading Google-PaLM Subscribing to mutations Error on request attempt 1 Error on request attempt 2 Error on request attempt 3 Error on request attempt 4 Error on request attempt 5 Client initialized.
> 
> **Desktop (please complete the following information):**
> 
> * OS/Device: Windows 11
> * Environment: local
> * Node.js version: v19.6.0
> * Browser: Chrome
> * Generation API: Poe
> * Branch: dev (Same bug occurs with main)
> * Model: Sage (Happens with every model)
> 
> **Additional context** Have tried using the main branch, using different models, closing and reopening SillyTavern, still happens.

It's a strange thing, but I have the almost the same issue, the only difference is when I'm trying to generate for the first time from launch, it works, but the second time, when generating a new text or regenerating an existing one, the same error occurs, along with this one 
![image](https://github.com/SillyTavern/SillyTavern/assets/61659850/63f4357c-da1c-4de0-aa5d-0afbb3521c53)

**Comment by vfnm** [comment]
Something that I noticed is that it seems to work fine if the next swipe or the next message does not take too much time, but after 1-2 minutes, it needs a reconnect and manual purge of the context window to work again properly. Perhaps it's possible to send a request every few seconds to keep the connection alive?

**Comment by dakuown** [comment]
> Something that I noticed is that it seems to work fine if the next swipe or the next message does not take too much time, but after 1-2 minutes, it needs a reconnect and manual purge of the context window to work again properly. Perhaps it's possible to send a request every few seconds to keep the connection alive?

the same

**Comment by 0mniSci** [comment]
> Please screenshot your Poe settings. Do you have auto-purge enabled? Does clicking "Purge Poe chat" help?

![image](https://github.com/SillyTavern/SillyTavern/assets/92959011/059ff6f4-ffef-4c22-bbc0-a0694542b33b)
I don't think there is an auto-purge option, but purging the Poe chat does help. It would be better if it was automatically purged instead of manually.

**Comment by Cohee1207** [comment]
Poe is no longer supported. We give up on it.
