### ISSUE TITLE
[BUG] Click the "prompt" icon in chat message doesen't work

### ISSUE THREAD

**Issue by shadowlinyf** [SillyTavern/SillyTavern#709]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
clit the "prompt" button in chat message cause error in browser console

**To Reproduce**
for my instance, everytime click that "prompt" icon will cause the error

**Expected behavior**
should pop up the token usage dialog

**Screenshots**
no need

**Logs**
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at getStringHash (utils.js:91:33)
    at countTokens (openai.js:967:22)
    at getTokenCountOpenAI (openai.js:186:12)
    at getTokenCount (script.js:563:20)
    at promptItemize (script.js:3181:33)
    at HTMLDivElement.<anonymous> (script.js:7758:13)
    at HTMLDocument.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)
```
The line cause the error should be this one[promptItemize (script.js:3181:33)]:
```
var zeroDepthAnchorTokens = getTokenCount(itemizedPrompts[thisPromptSet].zeroDepthAnchor);
```

**Desktop (please complete the following information):**
 - OS/Device: windows10
 - Environment: [local]
 - Node.js version (if applicable): v18.16
 - Browser chrome
 - Generation API : claude openai,should not related to the api
 - Branch [main, dev] dev (5812e34d)
 - Model [e.g. Pygmalion 6b, LLaMa 13b] claude2 claude1 gpt3.5

**Comment by shadowlinyf** [comment]
> Updated here: [8987534](https://github.com/SillyTavern/SillyTavern/commit/8987534403630366aec3a2cb9a044ad70c2f0ea1) See if the issue persists for you.

It is fixed now. Thank you. 
I am closing this issue.
