### ISSUE TITLE
[BUG] Could not extract reply in 5 attempts. Try generating again

### ISSUE THREAD

**Issue by Flufwuku** [SillyTavern/SillyTavern#731]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**

I was chatting normally with a bot until they start not responding, then that Error appeared, i try other bot, but it didnt work too.

**To Reproduce**
1. Go to Silly Tavern
2. Click on a Bot Chat
3. Write a Response

**Expected behavior**

None.

**Screenshots**

![ERROR](https://github.com/SillyTavern/SillyTavern/assets/139838051/582833ff-18f8-4392-84d0-b247d639f534)

**Logs**

982Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
script.js:2117 Core/all messages: 80/80
script.js:2584 pushed prompt bits to itemizedPrompts array. Length is now: 10
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
poe.js:270 Could not jailbreak the bot
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
script.js:2117 Core/all messages: 80/80
script.js:2584 pushed prompt bits to itemizedPrompts array. Length is now: 11
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
poe.js:270 Could not jailbreak the bot
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
script.js:2117 Core/all messages: 80/80
script.js:2584 pushed prompt bits to itemizedPrompts array. Length is now: 12
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
poe.js:270 Could not jailbreak the bot
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
script.js:2117 Core/all messages: 80/80
script.js:2584 pushed prompt bits to itemizedPrompts array. Length is now: 13
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
poe.js:270 Could not jailbreak the bot
:8000/generate_poe:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
script.js:2800 Error: Generate circuit breaker interruption
    at throwCircuitBreakerError (script.js:3419:11)
    at onSuccess (script.js:2740:29)
    
 
Desktop:
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version: v18.16.1
 - Browser: Chrome
 - Generation API: Poe
 - Branch: dev
 - Model: Sage

**Additional context**
None.

**Comment by GrayTheGris** [comment]
same here. A day has passed and even so it does not restore the uses of the bot

**Comment by GrayTheGris** [comment]
@Cohee1207  I solved it with a vpn, it is not a definitive solution and my ip is from Asia but hey, thanks for your kindness.

**Comment by Cohee1207** [comment]
Poe is no longer supported. We give up on it.

**Comment by GrayTheGris** [comment]
Well, I'm going to use Kobold horde again

**Comment by SpekFox** [comment]
I'm using Koboldcpp + ST and I have the same problem. There were no such mistakes in connection with Obabooga. This is probably somehow connected with the incorrect transfer of the result from Kobald to ST, because in the Kobold console the following:

Processing Prompt (1 / 1 tokens)
Generating (1 / 431 tokens)
(EOS token triggered!)
ContextLimit: 3422/4096, Processing:0.60s (605.0ms/T), Generation:0.01s (5.0ms/T), Total:0.61s (1.64T/s)
Output:

ST:
(node:21800) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.

**Comment by Cohee1207** [comment]
No, you are interpreting it incorrectly. Koboldcpp produced only one token - EOS. Which is essentially an empty string. This is likely because of using wrong prompt template.
