### ISSUE TITLE
[BUG] Poe freesockets error

### ISSUE THREAD

**Issue by SomeGuyU** [SillyTavern/SillyTavern#741]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes.

**Describe the bug**
It seems poe.com has removed Sage for some reason, but eitherway, its impossible to log in using poe right now.

**To Reproduce**
1. Go to the api section
2. Click on 'poe'
3.Try inserting any poe cookie
4. Bam, you get the 'Error saved to poe-error.log Free socket? true'
![imagem_2023-07-19_114146468](https://github.com/SillyTavern/SillyTavern/assets/117239425/59b6a322-d2a3-4929-ad7a-fba921014e12)

**Comment by SnowWhite0106** [comment]
I get the same error. Also looked up the poe site, my Sage is  called 'assistant' now, there are old chat logs. Tried a new poe cookie, didn't work either.

**Comment by IvKir** [comment]
Same issue here - 
And in poe-error.log i got this:

"message": "Request failed with status code 403",
"name": "AxiosError",
"stack": "AxiosError: Request failed with status code 403\n    at settle (%path-to-sillytavern%\\SillyTavern\\node_modules\\axios\\dist\\node\\axios.cjs:1909:12)\n    at Unzip.handleStreamEnd (%path-to-sillytavern%\\SillyTavern\\node_modules\\axios\\dist\\node\\axios.cjs:2989:11)\n    at Unzip.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",

**Comment by SomeGuyU** [comment]
> Try git pulling, there was a proposal solution pushed to both branches today

How would i do that? (im literally the most non understanding being on this planet, please forgive me)

**Comment by 4ballz** [comment]
I tried git pulling, downloading a whole new silly tavern, both the dev and main one, still the same issue.

**Comment by SnowWhite0106** [comment]
> Try git pulling, there was a proposal solution pushed to both branches today

The problem occured after doing a git pull. I even updated my node.js but the issue persists.

**Comment by IvKir** [comment]
I guess they somewhat preventing connection through 3rd parties.

**Comment by SomeGuyU** [comment]
> If that doesn't work, there's currently no solution from us. Remember that Poe is an unofficial client with zero endorsements from poe.com itself. And they could take active measures to prevent 3rd parties from accessing their site because it's in their rights.

Oof.

**Comment by Mohmadmiui** [comment]
So... does that mean no more poe?

**Comment by SomeGuyU** [comment]
> So... does that mean no more poe?

From what i understood, basically.

**Comment by LegionInstaller** [comment]
That sucks Time to use OpenAI then

**Comment by Woisek** [comment]
> That sucks Time to use OpenAI then

An expensive hobby then ...

**Comment by Mohmadmiui** [comment]
> That sucks Time to use OpenAI then

Dammit, I can't use openai or slack because I from Russia…

**Comment by chartongeston** [comment]
alternatives to poe/sage?

**Comment by Cohee1207** [comment]
Any other supported API. Try OpenRouter, it has Claude and GPT

**Comment by 4ballz** [comment]
The only other alternative I have is horde, even then it's not that good. Open router and novel are out of credits, and I can't figure out Kobold or Ooba.

**Comment by Cohee1207** [comment]
Poe is no longer supported. We give up on it.
