### ISSUE TITLE
[BUG] Unsupported colab issue

### ISSUE THREAD

**Issue by Juan-Cruz-Iturrioz** [SillyTavern/SillyTavern#770]
Have you searched for similar [bugs]
Yes

Describe the bug
FATAL: Could not write default file: public/settings.json Error: ENOENT: no such file or directory, copyfile 'default/settings.json' -> 'public/settings.json'

FATAL: Could not write default file: public/css/bg_load.css Error: ENOENT: no such file or directory, copyfile 'default/bg_load.css' -> 'public/css/bg_load.css'

FATAL: Could not write default file: config.conf Error: ENOENT: no such file or directory, copyfile 'default/config.conf' -> 'config.conf'

Error: Cannot find module '/SillyTavern/config.conf'

these messages are generated because the 
"SillyTavern/server.js" does not change the path of the settings.json, bg_load.css, config.conf

To Reproduce
1. Go to (https://colab.research.google.com/drive/1ZqC1Se43guzU_Q1U1SvPEVb6NlxNQhPt?usp=sharing)
2. Click Start TextGen WebUI
3. Scroll down to terminal
4. Wait 5 or 10 minutes
5. See error

Expected behavior
which works the same as version 1.8.2

Screenshots
![Captura de pantalla 2023-07-24 a la(s) 12 49 03](https://github.com/SillyTavern/SillyTavern/assets/89535004/d38ecc6d-2dc9-4c8a-a56e-0d7e8a2af852)
![Captura de pantalla 2023-07-24 a la(s) 12 49 17](https://github.com/SillyTavern/SillyTavern/assets/89535004/0260e500-4b17-4ce7-b89f-79e5e9b8980d)

Logs
FATAL: Could not write default file: public/settings.json Error: ENOENT: no such file or directory, copyfile 'default/settings.json' -> 'public/settings.json'
    at Object.copyFileSync (node:fs:2902:3)
    at createDefaultFiles (/SillyTavern/server.js:18:20)
    at Object.<anonymous> (/SillyTavern/server.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'default/settings.json',
  dest: 'public/settings.json'
}
FATAL: Could not write default file: public/css/bg_load.css Error: ENOENT: no such file or directory, copyfile 'default/bg_load.css' -> 'public/css/bg_load.css'
    at Object.copyFileSync (node:fs:2902:3)
    at createDefaultFiles (/SillyTavern/server.js:18:20)
    at Object.<anonymous> (/SillyTavern/server.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'default/bg_load.css',
  dest: 'public/css/bg_load.css'
}
FATAL: Could not write default file: config.conf Error: ENOENT: no such file or directory, copyfile 'default/config.conf' -> 'config.conf'
    at Object.copyFileSync (node:fs:2902:3)
    at createDefaultFiles (/SillyTavern/server.js:18:20)
    at Object.<anonymous> (/SillyTavern/server.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'default/config.conf',
  dest: 'config.conf'
}
Running from source
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '/SillyTavern/config.conf'
Require stack:
- /SillyTavern/src/middleware/basicAuthMiddleware.js
- /SillyTavern/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/SillyTavern/src/middleware/basicAuthMiddleware.js:10:16)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/SillyTavern/src/middleware/basicAuthMiddleware.js',
    '/SillyTavern/server.js'
  ]
}

Desktop (please complete the following information):
 - OS/Device: [Colab]
 - Environment: [cloud]
 - Node.js version (if applicable): [run `node --version` in cmd]
 - Browser [chrome]
 - Generation API [oobabooga/text-generation-webui]
 - Branch [main]
 - Model [LLaMa 2 13b]

Additional context

![Captura de pantalla 2023-07-24 a la(s) 12 48 34](https://github.com/SillyTavern/SillyTavern/assets/89535004/8f879cdc-42f1-4fdf-a578-7e2230d14a33)

**Comment by Cohee1207** [comment]
I'm sorry, but we have no relation to this colab. You need to find the maintainers and ask them to do the change.
