### ISSUE TITLE
[BUG] An unknown error occured while counting tokens

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#984]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, searched tokens and token [bug].

**Describe the bug**
I went to an old group chat to test something and this error popped up. It does not allow me to send any messages afterwards and spits out the same message. As seen in the logs it does seem something to do with group chats.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/6b1e0107-b817-4b77-a914-5084e08b7c41)

**To Reproduce**
1. Go to a old chat (immedialty 5 seconds after I would see this message)

**Expected behavior**
No error.

**Logs**

<details>
  <summary>F12 Logs (click to expand)</summary>

  # Developer Console Log
  ```js
  en-us
RossAscends-mods.js:156 Device type: desktop
(index):74 Object
(index):76 en
openai.js:2649 OpenAI model changed to gpt-3.5-turbo-16k-0613
power-user.js:418 applying bubblechat
system.js:115 Using default TTS Provider settings
system.js:148 Settings loaded
index.js:31 Array(1)
thumbnail:1     Failed to load resource: the server responded with a status of 404 (Not Found)
moment.js:287 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: July 5, 2023 2:28am, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://127.0.0.1:8000/lib/moment.min.js:1:3257)
    at Nt (http://127.0.0.1:8000/lib/moment.min.js:1:21587)
    at Pt (http://127.0.0.1:8000/lib/moment.min.js:1:22164)
    at W (http://127.0.0.1:8000/lib/moment.min.js:1:22247)
    at f (http://127.0.0.1:8000/lib/moment.min.js:1:207)
    at timestampToMoment (http://127.0.0.1:8000/scripts/utils.js:318:9)
    at addOneMessage (http://127.0.0.1:8000/script.js:1553:24)
    at http://127.0.0.1:8000/script.js:1268:9
    at Array.forEach (<anonymous>)
    at printMessages (http://127.0.0.1:8000/script.js:1267:10)
B @ moment.js:287
script.js:5209 Using default persona user-default.png
index.js:200 No current task
script.js:2583 Core/all messages: 35/35
PromptManager.js:1197 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getTokens')
    at PromptManagerModule.populateLegacyTokenCounts (PromptManager.js:1197:54)
    at PromptManagerModule.setChatCompletion (PromptManager.js:1167:10)
    at prepareOpenAIMessages (openai.js:864:23)
    at runGenerate (script.js:2990:40)
    at Generate (script.js:2760:9)
  }
  ```
</details>

<details>
  <summary>CMD Logs (click to expand)</summary>

# CMD Log
``` bash

call npm install --no-audit

up to date in 395ms

40 packages are looking for funding
  run `npm fund` for details
Running from source
SillyTavern 1.9.7 'staging' (76764091)
Stats loaded from files.
Launching...
SillyTavern is listening on: http://0.0.0.0:8000/

0.0.0.0 means SillyTavern is listening on all network interfaces (Wi-Fi, LAN, localhost). If you want to limit it only to internal localhost (127.0.0.1), change the setting in config.conf to “listen=false”

Instantiated the tokenizer for gpt-3.5-turbo

```
</details>

**Desktop (please complete the following information):**
 - OS/Device: Win 11
 - Environment: local
 - Node.js version (if applicable): v18.15.0
 - Browser: chrome
 - Generation API: OpenAI(proxy)
 - Branch: staging
 - Model: open ai 16k

**Comment by imesha10** [comment]
Ok now I tried to make new group chats. It's still happening with those too. 
I decided to check by deleting the old group and group chat folder from the public folder. Still does not work.
Strange, it was working just a little while ago.

**Comment by Cohee1207** [comment]
A fix for this has been merged.

**Comment by imesha10** [comment]
Works!
